### ISSUE TITLE
Remove support for the old standard when it's no longer needed

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#123]
The code and tests supporting the old standard (up to Firefox 45) should be removed when it's no longer necessary.
Firefox 45 is an ESR release, so we're going to need to keep it around for a while.

**Comment by marco-c** [comment]
Actually, Service Workers and Web Push have been disabled for Firefox 45 ESR (see https://developer.mozilla.org/en-US/Firefox/Releases/47#Service_Worker_and_related_APIs and https://bugzilla.mozilla.org/show_bug.cgi?id=1232029).
So we can remove the old standard as soon as Firefox 46 is released.

**Comment by shobhitic** [comment]
Do you know what do they mean by disable for Firefox 45? Will the notifications not work in 45 going forward?

**Comment by marco-c** [comment]
It's been disabled only for the ESR version (https://www.mozilla.org/en-US/firefox/organizations/).
The normal Firefox 45 (and the following versions) still supports push notifications.

**Comment by shobhitic** [comment]
Ahh. But then, if the old standard is removed as soon as FF 46 is released, will it still be able to deliver pushes to FF 45?

**Comment by marco-c** [comment]
> Ahh. But then, if the old standard is removed as soon as FF 46 is released, will it still be able to deliver pushes to FF 45?

I will not remove it right away, I'll remove it after a while (when everyone will have updated to Firefox 46).

**Comment by marco-c** [comment]
I will remove support for the old standard a week after the release date of Firefox 47.

**Comment by gbhrdt** [comment]
Some of my users still use Firefox 45. Please still keep this feature for a while!

**Comment by marco-c** [comment]
> Some of my users still use Firefox 45. Please still keep this feature for a while!

Service Workers and Web Push aren't supported in Firefox 45 ESR.

If they use Firefox 45 non-ESR, they really should update for security reasons! You can use an older version of the library if you really want to support them.
