### ISSUE TITLE
Support Firefox OS Simple Push (?)

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#17]
I guess this could be useful for apps targeting older versions of Firefox OS.

**Comment by marco-c** [comment]
There's an example here: https://github.com/arcturus/firefox-os-simplepush

**Comment by gauntface** [comment]
Worth closing this?

**Comment by marco-c** [comment]
Yes, definitely!

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1296579
