### ISSUE TITLE
Unsupported method ('POST')

### ISSUE THREAD

**Issue by viniciusdepaula** [web-push-libs/web-push#177]
Hi,

I'm getting the the following messages:

"NetworkError: 501 Unsupported method ('POST') - http://localhost:8000/register"
"NetworkError: 501 Unsupported method ('POST') - http://localhost:8000/sendNotification"

Do you have some idea of what may be occurring?

Thanks in advance.

**Comment by marco-c** [comment]
This doesn't seem related to this library but to the way you implemented your server.

**Comment by marco-c** [comment]
Looks like your server doesn't implement the POST method and you're trying to use it.
