### ISSUE TITLE
Reenable automated tests for Firefox

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#179]
The preferences to automatically accept the push permission prompt are not being set for Marionette. Once we figure out the problem and it is fixed (either on the Marionette side or on ours), we can remove https://github.com/web-push-libs/web-push/blob/8a8e900c4c76fd198142f859d135397901edac72/test/testSelenium.js#L54 and https://github.com/web-push-libs/web-push/blob/8a8e900c4c76fd198142f859d135397901edac72/test/testSelenium.js#L38 and let Firefox tests run on Travis.

**Comment by marco-c** [comment]
In theory, we could manually set the preferences, like what we're doing for Chrome.

**Comment by gauntface** [comment]
It looked like the permissions were being stored in an sqlite db, do you know if that's the case?

**Comment by marco-c** [comment]
They are JS files, some of them are in the Firefox installation directory, others are in the profile directory (https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences#Preferences_files).

We could create a `user.js` file in the profile directory.

**Comment by gauntface** [comment]
That sounds like a much better approach that the permissions preference if it'll work.

**Comment by marco-c** [comment]
Oh, sorry, I wasn't clear. With this approach we would still use the preference, only we will add it manually instead of relying on Marionette to do it.

I'm not sure if it is feasible or if it's just better to wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1275521 to be fixed.

**Comment by marco-c** [comment]
@andreastt and @jgraham, do you have an estimate on when the bug will be fixed? Do you have an alternative solution that we could use here?

**Comment by marco-c** [comment]
https://github.com/SeleniumHQ/selenium/pull/2406

**Comment by andreastt** [comment]
The PR @marco-c linked to fixes the immediate problem that preferences aren’t being propagated to Firefox through geckodriver. I verified that with this patch applied to the selenium-webdriver Node.js bindings, the profile geckodriver is using is being used by Firefox.

However, I could not get either of these preferences to work:

```js
ffProfile.setPreference('security.turn_off_all_security_so_that_viruses_can_take_over_this_computer', true);
ffProfile.setPreference('dom.push.testing.ignorePermission', true);
ffProfile.setPreference('notification.prompt.testing', true);
ffProfile.setPreference('notification.prompt.testing.allow', true);
```

**Comment by marco-c** [comment]
Using https://github.com/SeleniumHQ/selenium/pull/2407 is also another option.

In theory with https://github.com/SeleniumHQ/selenium/pull/2407 we'd be able to support every Firefox version, with the preferences instead we'd just be able to support Firefox >= 49.

**Comment by gauntface** [comment]
@marco-c are you aware of any changes with this / any avenues we can take to get automated tests back up and running?

**Comment by marco-c** [comment]
Selenium 3.0.0-beta-1 should include the changes from https://github.com/SeleniumHQ/selenium/pull/2407 (https://github.com/SeleniumHQ/selenium/issues/2514#issuecomment-238035196), so if we use it our tests should work.

**Comment by marco-c** [comment]
@gauntface I think in order to use selenium-webdriver 3.0.0-beta-1 we also need to modify https://github.com/GoogleChrome/selenium-assistant, as it requires 2.53.

**Comment by gauntface** [comment]
Working on that just now. Nearly there.

**Comment by gauntface** [comment]
FYI release beta version of selenium-assistant that uses selenium-webdriver beta https://github.com/GoogleChrome/selenium-assistant/releases/tag/v0.4.0-beta
