### ISSUE TITLE
gcmAPIKey is a global variable

### ISSUE THREAD

**Issue by nikhil32** [web-push-libs/web-push#181]
Hi,

I had a plan of hosting this web-push as a seperate rest server so that my java application will use it to send push notifications. I can have parallel threads running on java calling this server with different API keys. Since gcmAPIKey is a global variable, it can cause issues to me. How about having it also as a parameter in sendNotification as a optional overriding parameter. just a suggestion.

**Comment by gauntface** [comment]
@nikhil32 is your use case a scenario where anyone can send a push message through your server?

**Comment by nikhil32** [comment]
@gauntface yes, we have a single application server on our side with multiple accounts. we are planning to have multiple gcm accounts to multiple accounts but from single app server.

**Comment by marco-c** [comment]
Isn't Node.js single threaded? You can simply call `setGCMAPIKey` and `sendNotification` one after another and, given that Node.js is single threaded, this shouldn't cause any issue. Or am I missing something?

**Comment by gauntface** [comment]
It is, but I can't help but feel like that could break fairly easily. Say sendNotification() returns a new Promise as the very start of it's execution, with that, there is the possibility that node will create a seperate task for the work load, run the code setting the GCM API Key before getting round to the workload in the new promise, after which the GCM API Key will no longer be valid.

**Comment by marco-c** [comment]
Yes, I agree that it's brittle. It's unlikely that it will break, as I don't think we will move the code that uses the key to a promise handler, but it would be better to be 100% sure.

I see two options:
1) Store the key in a local variable at the beginning of `sendNotification` with a big explanatory comment;
2) Add the overloading parameter to `sendNotification` as @nikhil32 suggested;
3) Add the parameter to `sendNotification` and completely remove `setGCMAPIKey`.

I'm leaning towards 2 or 1, as I'd rather not break compatibility for this unusual use case.

**Comment by gauntface** [comment]
I'd be in favor of option 2. Make if a part of the options object and sendNotification uses that as the GCM API key if it's set, otherwise it falls back to the globally set gcm api key.
