### ISSUE TITLE
Check that the GCM API key is correct

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#185]
Right now we're blindly using it without checking if it is correct.
@gauntface do you know if there's some property of the API key that we can check to make sure it's valid?

**Comment by gauntface** [comment]
Afraid not. The best thing to do is ensure the following:

- The object is a string
- it isn't empty
- If there is a common status code or body that can be abstracted when a bad GCM API Key is used, return a helpful error message when the promise is rejected.
