### ISSUE TITLE
Promise resolved with failed response.

### ISSUE THREAD

**Issue by zdila** [web-push-libs/web-push#186]
Calling

`webPush.sendNotification(...).then(result => console.log('OK', result)).catch(err => console.log('ERR', err))`

printed

`OK {"multicast_id":4975198505024336652,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}`.

I would expect it to print `ERR ...`.

**Comment by marco-c** [comment]
I guess the server returned `200`, so the library assumed it was OK.

**Comment by zdila** [comment]
I see. The same way works https://github.com/ToothlessGear/node-gcm. Maybe it just could be mentioned in the docs.
