### ISSUE TITLE
Firefox stable no longer working

### ISSUE THREAD

**Issue by Xzya** [web-push-libs/web-push#188]
Whenever I send a notification to Firefox stable (tested 47.0 and 47.0.1) I get back an error with  
"{"errno": 106, "message": "No such subscription", "code": 410, "error": ""}"  
I tried unsubscribing/subscribing again so I don't see how the subscription might be missing, the token/userAuth/publicKey look ok. I don't think there's anything wrong with my server since the demos on https://serviceworke.rs seem to have stopped working also. It worked fine until about a week ago. It also works fine in Firefox Developer Edition 49.0a2  
Is this a problem with the library or Firefox itself? It seems strange to stop working all of a sudden.  
Also, Firefox Beta 48.0b4 on Android no longer works either, the error I get is  
"{"errno": 999, "message": "Please try request later.", "code": 503, "error": "Service Unavailable"}"  
This seems to indicate a problem with the mozilla services.

**Comment by marco-c** [comment]
Could you try again now? They're working for me.

**Comment by Xzya** [comment]
Yes, they're working now, so I guess it was a problem with the Mozilla services.  
Thanks!

**Comment by nikhil32** [comment]
Hi I am also getting the same issue with firefox subscriptions. It was working some time back

**Comment by marco-c** [comment]
I don't think this is an issue with the library, but rather with the push service.

@jrconlin do you have any insights?

**Comment by jrconlin** [comment]
@nikhil32 can you provide the error message and endpoint URL you're seeing? We're getting reports of problems and it would help us identify an issue.

**Comment by nikhil32** [comment]
@jrconlin yeah it is not only with this library. Even when tried directly withouy paylaod. I am getting the following response

{"multicast_id":8027766775208206947,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}

**Comment by jrconlin** [comment]
That's not an error we produce, which is odd. It looks like it might be a return from GCM directly.

Not to shift things, but we're also seeing occasionally odd returns on the server. We're getting odd results occasionally when we post things to GCM. They just started about a week ago or so, and we're still trying to nail down what might be going on. Not sure if you're sending to Android (which piggybacks on GCM) , or desktop (which doesn't).

**Comment by gauntface** [comment]
@jrconlin GCM has just started support web push protocol. Perhaps the two things are related?

**Comment by jrconlin** [comment]
Honestly, no idea, but I don't want to point fingers yet either.

**Comment by marco-c** [comment]
@jrconlin have you managed to figure out the problem?

I'm going to close this issue since it isn't related to this library, @nikhil32 if you're still experiencing the problem you could file an issue here: https://github.com/mozilla-services/autopush.

**Comment by jrconlin** [comment]
There were a few problems we saw with endpoints that have expired not being reported correctly, and some logging not getting made. We pushed a new version of the server last Thursday. We're still trying to hammer out the GCM bounce problem, but there are a lot of moving parts and not a lot of ways to get diagnostics.

+1 on filing issues on autopush.
