### ISSUE TITLE
No response from successful Firefox notification

### ISSUE THREAD

**Issue by kylebuch8** [web-push-libs/web-push#191]
When I send a message to Chrome, I get back a body with information like success, failure, message_id, etc... However, when I send a message to Firefox, I get back an empty body. Is this the expected result?

**Comment by froodian** [comment]
the mozilla service just returns status codes, so a 201 or 200 means success from firefox

**Comment by gauntface** [comment]
The reason you get a response from Chrome is because it's using the GCM API which is proprietary. Firefox uses the web push protocol to send messages. Chrome will be using the web push protocol in the next release of the web-push module.

**Comment by felixsanz** [comment]
When that happens, we don't need to use GCM api key or proyect ID in manifest.json right?
