### ISSUE TITLE
Change signature of sendNotification?

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#192]
At the moment the signature of sendNotification results in code along
the lines of:

```javascript
const webpush = require('web-push');

webpush.setGCMAPIKey(GCM_API_KEY);

const subscriptions = getSubscriptions();
subscriptions.forEach(subscription => {
  const params = {
      payload: 'some payload',
      vapid: {
        subject: 'mailto: myemail@myemail.com',
        publicKey: VAPID_KEYS.publicKey,
        privateKey: VAPID_KEYS.privateKey
      }
  };

  if (subscription.keys) {
      params.userAuth = subscription.keys.auth;
      params.userPublicKey = subscription.keys.p256dh;
  }

  webpush.sendNotification(subscription.endpoint, params);
});
```

This could be simplfied to:

```javascript
const webpush = require('web-push');

webpush.setGCMAPIKey(GCM_API_KEY);
webpush.setVapidDetails({
    subject: 'mailto: myemail@myemail.com',
    publicKey: VAPID_KEYS.publicKey,
    privateKey: VAPID_KEYS.privateKey
})

const subscriptions = getSubscriptsion();
subscriptions.forEach(subscription => {
  webpush.sendNotification(subscription, 'some payload');
});
```

If we wanted to, we could move VAPID and GCM to be optional params
, as requested in #181:

```javascript
const webpush = require('web-push');

const subscriptions = getSubscriptsion();
subscriptions.forEach(subscription => {
  const options = {
    gcmAPIKey: getGCMAPIKey(subscription),
    vapid: getVAPIDDetails(subscription)
  }
  webpush.sendNotification(subscription, 'some payload', options);
});
```

What do you think @marco-c @nikhil32?

**Comment by marco-c** [comment]
Both options look good to me. Maybe the first would be a smaller change compared to the second (it wouldn't change the signature for people who aren't using VAPID yet, which is the majority).

**Comment by gauntface** [comment]
I was thinking both would be implemented but it would be up to the developer how to pass in GCM and VAPID - Matching PR #193.

Would you be ok with me putting together this change as a PR?

It would be a breaking change so may do a major release at a later stage, but I think it would be a good and worthwhile change.

**Comment by marco-c** [comment]
> I was thinking both would be implemented but it would be up to the developer how to pass in GCM and VAPID - Matching PR #193.

> Would you be ok with me putting together this change as a PR?

OK, makes sense!

> It would be a breaking change so may do a major release at a later stage, but I think it would be a good and worthwhile change.

Yes, I was thinking the same. It won't be a breaking change for most users though (as most users are using GCM or Web Push without VAPID), so the earlier we make the change the better it is.

**Comment by nikhil32** [comment]
@gauntface @marco-c  thanks for the feature...
