### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#194]
At the moment the code is a little bit of a mix of practices, it would be good to get a coding style and enforce it with a Travis check. My default is to use the https://www.npmjs.com/package/eslint-config-google but happy to go with anything tbh (Maybe XO: https://github.com/sindresorhus/xo), just something to give consistency over time.

**Comment by marco-c** [comment]
I'm used to eslint-config-airbnb with some modifications, but I'm open to anything.

**Comment by gauntface** [comment]
Let's roll with that, do you have an example .eslintrc file with the modifications you'd use?

**Comment by marco-c** [comment]
Here's an example from another project: https://github.com/mozilla/serviceworker-cookbook/blob/master/.eslintrc

We would probably need to change some rules if we adopt it though, as IIRC it contains some ES6 rules.
