### ISSUE TITLE
support for microsoft edge web push

### ISSUE THREAD

**Issue by VenkateshSrini** [web-push-libs/web-push#199]
Hi,
With the window10 anniversary update, Microsoft edge can also listen to push notification. The current web push just uses the GCM endpoint only. Microsoft edge requires WNS endpoint to send push notification. Is it possible to add WNS end point also to this library. 
Can you please provide some guidance using which we can add the WNS end point also ?

This is the link that says the availability of Web push notification in Microsoft edge
https://blogs.windows.com/msedgedev/2016/05/16/web-notifications-microsoft-edge/

Thanks and regards
Venkatesh

**Comment by gauntface** [comment]
Do you have a link to any docs announcing push support or info on this?

**Comment by VenkateshSrini** [comment]
Hi Mathew,

Please see the link in my post

**Comment by VenkateshSrini** [comment]
https://blogs.windows.com/msedgedev/2016/05/16/web-notifications-microsoft-edge/

**Comment by VenkateshSrini** [comment]
Here are more link 
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webnotifications

**Comment by gauntface** [comment]
That's for the API to show a notification. The "Push API" is still in development.

Also worth noting this library supports web push protocol which hopefully edge will implement without proprietary bits like chrome did with GCM. If that's the case this library should just work.

**Comment by VenkateshSrini** [comment]
If at all there as an wns dependency then how to do we proceed
