### ISSUE TITLE
Match IETF draft Authorization header

### ISSUE THREAD

**Issue by benlast** [web-push-libs/web-push#200]
The `Authorization` header produced by this library includes `Bearer` as the scheme. The spec at [https://tools.ietf.org/html/draft-ietf-webpush-vapid-01](https://tools.ietf.org/html/draft-ietf-webpush-vapid-01) states that the scheme should be `WebPush` (https://tools.ietf.org/html/draft-ietf-webpush-vapid-01#section-3).

**Comment by marco-c** [comment]
I think FCM doesn't support this yet, but still requires `Bearer`.

Thank you for opening the issue, I never would have noticed the change.

**Comment by gauntface** [comment]
Will follow up on this tomorrow, thanks for the bug.

Does this currently break any browsers if we switch to this?

**Comment by marco-c** [comment]
> Does this currently break any browsers if we switch to this?

I've just tried to run the tests after the change, they're failing with Chrome, working with Firefox.

**Comment by gauntface** [comment]
Schweet thank you for the info
