### ISSUE TITLE
push notification are not delivered for firefox subscriptions

### ISSUE THREAD

**Issue by shivaprasadmanupadi** [web-push-libs/web-push#202]
subscriptions.forEach(function(subscription) {
                webPush.sendNotification(subscription.endpoint, {
                    userPublicKey: subscription.key,
                    userAuth: subscription.auth,
                    TTL: 10000
                })
                .then(function(data) {
                }, function(err) {
                    console.log(err);
                });
            });

this is my api to send push notification to all the subscriptions.
it is working fine with chrome subscriptions . here is my schema 

var subscriptionSchema = new Schema({
    endpoint: {
        type: String,
        required: ['endpoint is required.']
    },
    key: {
        type: String,
    },
    auth: {
        type: String,
    },
    browser: {
        type: String,
        required: ['browser is required.']
    },
    workspace_id: {
        required: ['invalid workspace id.'],
        type: Schema.Types.ObjectId,
        ref: 'workspace'
    },
    application_id: {
        required: ['invalid application id.'],
        type: Schema.Types.ObjectId,
        ref: 'application'
    },
    active: {
        type: Boolean,
        required: true,
        default: true
    }
}, {
    timestamps: {
        createdAt: 'created_at',
        updatedAt: 'updated_at'
    }
});

**Comment by marco-c** [comment]
What version of Firefox are you using? Which version of the `web-push` library?
Is there anything logged to the console?

**Comment by marco-c** [comment]
Please reopen if you can answer the questions.
