### ISSUE TITLE
Possible to add a 'GH_TOKEN' to Travis?

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#205]
One of the pain points of using Geckodriver is that it's releases are on Github meaning I need to parse the Github API response to get the latest release, which is hitting an API quote on Travis.

Is there anyway you can add a Github Access Token which should raise or allocate a different API limit (i.e. not a limit based on IP address).

**Comment by marco-c** [comment]
It's already there 😄 
Did you add it?

**Comment by gauntface** [comment]
Yeah - didn't realise I had access to the Travis settings.
