### ISSUE TITLE
Reduce size of install

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#207]
See : https://twitter.com/borismus/status/770456100235726849 from @borismus

**Comment by marco-c** [comment]
Maybe we could find a way to make the dependencies needed to support older Node.js versions optional.

**Comment by marco-c** [comment]
Another idea is to create PR to our dependencies to make them add a `.npmignore` file to avoid including tests in their packages, e.g. https://github.com/indutny/asn1.js/pull/75.

**Comment by marco-c** [comment]
With the new `http_ece` we're under 1 MB.

**Comment by marco-c** [comment]
List of packages where more files could be added to .npmignore: `typedarray`, `minimist`, `jws`, `jwa`, `base64url`. We would save around 135 kB.

**Comment by marco-c** [comment]
https://github.com/substack/typedarray/pull/11
https://github.com/substack/minimist/pull/95
https://github.com/brianloveswords/node-jws/pull/60
https://github.com/brianloveswords/node-jwa/pull/15
https://github.com/brianloveswords/base64url/pull/14

**Comment by marco-c** [comment]
I think we can call this fixed!
