### ISSUE TITLE
Change output and input of VAPID from Buffer to String

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#210]
I'm constantly hitting issues with messing with VAPID keys as it's a buffer that I need to get into the web page, convert to unit8array and then find a way to store the VAPID keys so that I can then get that value back out and pass into the web-push library.

Exporting and importing VAPID keys as base64 url safe strings at least makes storing and re-using easier with the web push libs and we can then provide an example of how to use this base64 url string as the applicationServerKey in the page.

@marco-c what do you think?

**Comment by ithinkihaveacat** [comment]
I'd prefer this, it took me a little while to realize what formats were required, and then another while to figure out how to do the conversions.

If it's useful, here's what [I ended up with](https://gist.github.com/ithinkihaveacat/79491c809e5e3262cdf1eca79f0c0926).

**Comment by marco-c** [comment]
Makes sense to me.
