### ISSUE TITLE
Test the CLI script

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#213]
We could write another Selenium test that executes the CLI script instead of calling the web-push functions.

**Comment by gauntface** [comment]
I was wondering what you're thoughts would be on the following:

Allowing two actions on the cli:

1. send-notification
2. generate-vapid-keys

The formation would be:

    web-push <Action> <Action-Options>

This would have usage of either:

    web-push send-notification --endpoint=<url> --key=<browser key> [--auth=<auth secret>] [--ttl=<seconds>] [--payload=<message>] [--vapid-audience] [--vapid-subject] [--vapid-pvtkey] [--vapid-pubkey]

    web-push generate-vapid-keys [--json]

The output of `generate-vapid-keys` would be something along the lines of:

    $web-push generate-vapid-keys
    
         ======================================
         Public Key:
         1234567890123456678990

         Private Key:
         12345678901234567890
          ======================================

The idea being if a developer was just starting out, they could get a set of VAPID keys without actually having to run a node script first to then change the script.

**Comment by marco-c** [comment]
Sounds good to me, we could also add it to the documentation in the `Usage` section.
