### ISSUE TITLE
webPush.sendNotification returns getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by grrrian** [web-push-libs/web-push#215]
When I call:
```
     webPush.setGCMAPIKey(FIREBASE_GCM_SERVER_KEY);
      return webPush.sendNotification(_.get(req, 'body.pushEndpoint.to'), {
        payload: JSON.stringify(_.get(req, 'body.payload')),
        userPublicKey: _.get(req, 'body.userPublicKey'),
        userAuth: _.get(req, 'body.userAuth')
      })
      .then(function() {
        console.log('DONE');
        res.send(200);
        return next();
      }, function(error) {
        console.log('error: ', error);
      }));
```
I'm getting the following error: 
```
{ [Error: getaddrinfo ENOTFOUND apa91... apa91...:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'apa91...',
  host: 'apa91...',
  port: 443 }
```

`getaddrinfo ENOTFOUND` means the client was not able to connect to given address. Does anyone know why? Is it because I am on localhost?

**Comment by kitcambridge** [comment]
That `apa91...` hostname seems rather curious. What does `_.get(req, 'body.pushEndpoint.to')` return when you get that error?

**Comment by grrrian** [comment]
I just truncated the string to make my question shorter. There are many other characters after apa91. Body.PushEndpoint.to is also fine: a long string resembling Xxx:yyyyyy....

ian

**Comment by ithinkihaveacat** [comment]
@grrrian The endpoint (first argument to `sendNotification()`) should be an actual URL beginning with `https` such as 

- <https://updates.push.services.mozilla.com/wpush/v1/gAAAAABXtbKwIC1N_b4-2ShWeXsFIhvTSVknOP0BCLIcZaOJN3KyKUrRcES2Dcl3bu0_EWbOvVNLYV-fK6MdSYbxM-Ad_d0xh4VxL-ahfNIu5ZbglyL3XVPu5sY6UlgaM41TIKfk_IZo> (Mozilla)
- <https://fcm.googleapis.com/fcm/send/evfkzh0-7sQ:APA91bHc00Y9_SvpwLexp1k6af2qsqOCXdNRV7P-1z1XRmTD_Cn8m29DPaq6xISqTnh2nBhi3cHIujS23uiGpQbE-Ed8ztZFM3vYZqZIBsfJgb6OAuacVdvSFs6V-22RTo8QL6bOsDjr> (Chrome)

**Comment by grrrian** [comment]
ahhhhh thank you so much!

**Comment by grrrian** [comment]
hmmm... now i'm getting a different error :(

```"<HTML>
<HEAD>
<TITLE>UnauthorizedRegistration</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>UnauthorizedRegistration</H1>
<H2>Error 400</H2>
</BODY>
</HTML>
"```
