### ISSUE TITLE
Success not returning request body

### ISSUE THREAD

**Issue by mbrevda** [web-push-libs/web-push#222]
The [readme](https://github.com/web-push-libs/web-push/blame/master/README.md#L30) says:
> The function returns a Promise. On success, it is resolved to the body of the response

However, the response is always blank.

I assume the reason this isn't working is because the version npm is two months old. Can we please get a newer version pushed to npm?

**Comment by marco-c** [comment]
It is working, it's just that the push service is returning an empty response.

To be honest, I think you shouldn't really care about the response from the push service, unless you're debugging.

For example, go to https://serviceworke.rs/push-simple_demo.html and try the curl command on your machine.

**Comment by mbrevda** [comment]
The reason for my "concern" was to try and detect old/stale tokens and
remove them from my db. Or is that not how it works?

**Comment by marco-c** [comment]
When a token expires, the push service will respond with an error, and the promise will be rejected.

See for example https://serviceworke.rs/push-subscription-management_server_doc.html.

**Comment by mbrevda** [comment]
thanks!
