### ISSUE TITLE
Tag releases on Github

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#223]
Maybe use https://github.com/GoogleChrome/npm-publish-scripts

**Comment by marco-c** [comment]
Actually, I had the tags locally, but forgot to push them.
I'm using the `npm version` command, which creates a commit for the version and the tags for me: https://docs.npmjs.com/cli/version.

I'm OK with switching to `npm-publish-scripts` if you want, documentation on GitHub pages might be useful

**Comment by marco-c** [comment]
I'm going to close this since I'm already tagging the versions, but feel free to open a new issue if you want to talk about using `npm-publish-scripts`.
