### ISSUE TITLE
Drop support for older versions of Node.js

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#225]

**Comment by marco-c** [comment]
This will also help with #207, as we can remove some unused code and drop some unneeded dependencies (e.g. `bluebird` is ~600 kB).

**Comment by gauntface** [comment]
Looking through this:

- buffer-compare-shim
    We don't actually use buffer.compare anywhere, so I think it's safe to be dropped.
- array.prototype.find
    The only places we use find are in the tests so against safe to drop
- bluebird
    Would be good to drop.
- buffer-equals-polyfill
    Looks like it'sused in tests only
- create-ecdh
    Can be dropped


That'll leave use with:

------------------------------------------------------------------------------
| Dependency                    | Time | Size     | # Deps |
------------------------------------------------------------------------------
| jws                                    | 8.2s | 611 KB | 24         |
| http_ece                           | 6.8s | 762 KB | 19         |
| asn1.js                             | 3.7s | 293 KB | 3            |
| urlsafe-base64               | 2.8s | 18 KB    | 0           |
| minimist                          | 2.8s | 48 KB    | 0           |
------------------------------------------------------------------------------

- Minimist is require by the CLI.
- urlsafe-base64 is used pretty heavily throughout.
- asn1.js I've never groked what it does
- http_ece looks good (although it has dependencies on polyfills that we'd be dropping)
- JWS I'm slightly confused where the number of deps came from given that it has only 2 on npm. Thought it may include nested dep's, still couldn't reach 24.

**Comment by marco-c** [comment]
We can probably create a PR for `http_ece` to drop support for older Node.js versions. Martin added it simply because of the Firefox Accounts server, but now that they've updated it doesn't make sense anymore.

`asn1.js` is used to convert a key to PEM. We could probably write our own, implementing only this feature.
