### ISSUE TITLE
Next Major Release

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#226]
If I can get #213 sorted, do you think we could perform a major release next week?

**Comment by marco-c** [comment]
Yes, I think it's time to do it.

**Comment by marco-c** [comment]
Do you think we should keep compatibility with 0.10 and 0.12 for the next version or should we drop it now?

If we don't drop it now, we might want to wait for the subsequent major release.

Another option is to release version 3.0.0, still compatible with 0.10 and 0.12 and quickly, right after fixing #225, releasing version 4.0.0.
We could publish them at the same time, so people won't notice. Someone might find it weird to go from version 2 to version 4.

**Comment by gauntface** [comment]
I'm pretty sure the CLI won't work on 0.10 or 0.12 but the core library should work.

But saving it for a major release makes sense and personally I'd rather do it now for 3.0.0 release so we can iterate and remove the cruft in 3.x.x releases.

**Comment by marco-c** [comment]
Sounds good, I'll do it now.

**Comment by marco-c** [comment]
I'm planning to release the next version tonight. Anything you wanted to do before that?

**Comment by gauntface** [comment]
Nope, that changes you landed for 4.0 support looked good. Release away :)

**Comment by gauntface** [comment]
p.s. What time zone are you? I'm PST

**Comment by marco-c** [comment]
Done! 0b08002bcbc9bccae5e448ab185c07755bb5bcd3

> p.s. What time zone are you? I'm PST

GMT

**Comment by marco-c** [comment]
> GMT

Actually, GMT+1 at the moment (London).
