### ISSUE TITLE
When is keyid=p256dh; needed?

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#234]
I only noticed this today: https://github.com/web-push-libs/web-push/blob/master/src/web-push-lib.js#L167

        requestOptions.headers.Encryption = 'keyid=p256dh;salt=' +
          encrypted.salt;
        requestOptions.headers['Crypto-Key'] = 'keyid=p256dh;dh=' +
          urlBase64.encode(encrypted.localPublicKey);

I've not used the keyid anywhere in my simple push demo and just wondering when it would be needed? Looking at the spec for web push protocol the only reference I found was:

>   An application server MUST include exactly one entry in the
>   Encryption field, and at most one entry having a "dh" parameter in
 >  the Crypto-Key field.  This allows the "keyid" parameter to be
 >  omitted from both header fields.

**Comment by kitcambridge** [comment]
I think it's only needed if you're using VAPID, where you end up with two keys in `Crypto-Key`.

**Comment by gauntface** [comment]
When using vapid I have been using:

Crypto-Key:
dh=BIUOQulbuyhxAxrPJmAhBt5AfCFHxu3LjSqGrynrDfQfaVAYY4fxYKlKMCR0y45Xs1aXlJQwKN5TCV7I6kLLFi0;
p256ecdsa=BDd3_hVL9fZi9Ybo2UUzA284WG5FZR30_95YeZJsiApwXKpNcF1rRPF3foIiBHXRdJI2Qhumhf6_LFTeZaNndIo

Format and it's working for me.

**Comment by kitcambridge** [comment]
Oh, nice! You're totally right, the `keyid` doesn't seem to be needed at all.

**Comment by marco-c** [comment]
From https://blog.mozilla.org/services/2016/08/23/sending-vapid-identified-webpush-notifications-via-mozillas-push-service/:
> “keyid” is the string “p256dh”. Normally, “keyid” is used to link keys in the Crypto-Key header with the Encryption header. It’s not strictly required, but some push servers may expect it and reject subscription updates that do not include it. The value of “keyid” isn’t important, but it must match between the headers.

I guess we can remove it if we find that it isn't needed by any server.
