### ISSUE TITLE
Add Urgency Support / More generic way to add additional headers?

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#235]
I wasn't aware of the Urgency header until I noticed it in the web-push-php library.

https://tools.ietf.org/html/draft-ietf-webpush-protocol-10#section-5.3

Given that this requires extra support from us and issue #211 

I'm wondering if it makes sense to support adding arbitrary headers, something along the lines of:

```
webpush.sendNotification(subscription, payload, {
    headers:  {
        'Urgency': 'value',
        'Topic': 'value',
        'Future-Header': 'value'
    }
});
```

We can then support future headers without needing to do anything and we can add additional and checks if we want to.

Main downside is that it's exposing the implementation of web push protocol somewhat and we probably should move TTL into headers if we move forward with this.

The alternative is we grow the options object, but it will require explicit support for new headers.

```
webpush.sendNotification(subscription, payload, {
      'Urgency': 'value',
      'Topic': 'value',
      'Future-Header': 'value'
});
```

@marco-c What do you think?

**Comment by marco-c** [comment]
What about adding the options *and* supporting an `headers` option?
This way we hide the implementation of the web push protocol for most people (who are going to use
the options) but still allow to define new headers before we officially support them.

**Comment by delapuente** [comment]
Gonna implement this. I will start by adding the `headers` options. I have a doubt, if both the header in the `headers` key and the specific keys are provided, which one wins?

```js
webpush.sendNotification(subscription, payload, {
  headers: {
    'Topic': 'value'
  },
  'Topic': 'another-value'
});
```

In my opinion, the header should be `Topic: another-value` which means to make the specific win but it also can be the reverse or the latest, for instance. What do you think?

**Comment by gauntface** [comment]
I'd throw an error if a header is defined twice and just enforce not allowing it.

**Comment by gauntface** [comment]
p.s. thanks for picking this up :)

**Comment by delapuente** [comment]
In case of rejecting, which kind of error should the library throw?

**Comment by gauntface** [comment]
new Error(`Duplicate headers defined [${duplicates.join(', ')}]. Please either define the header in top level options OR in the headers object, not both.`);

**Comment by delapuente** [comment]
Makes sense. Thank you.

**Comment by delapuente** [comment]
I'm wondering if there should be a black list of headers to throw in case of attempting to overwrite `Content-Length` for instance (this is currently harmless, anyway). I don't know what is better when checking duplicated values for Encription. The consistent way would be to check manually for the specific keys and see if the user is providing the matching headers in the `header` option. Another way could be to enforce top level properties for auth and VAPID.

What do you think?

**Comment by gauntface** [comment]
Could you explain a little more what you mean / provide some examples?

**Comment by gauntface** [comment]
My gut is saying we should set the defaults with the ones provided in the headers object and then any headers than are altered after this by the library should either take into account the user provided header OR overwrite the user provided header.

If it's easier to move **all** values into the headers object rather than be top level options object I'd be open that, but will be another annoying change for developers :(
