### ISSUE TITLE
Generic client for Webpush

### ISSUE THREAD

**Issue by Black-Star** [web-push-libs/web-push#236]
Can we have a generic client for sending a notification.

For example:
```js

var client = new WebPush({ 'GCMAPIKey': '***********************' })
client.sendNotification(subscription, payload, options).then(function(success) {
  console.log(success);
}, function(error) {
  console.log(error);
});

```

**Comment by ithinkihaveacat** [comment]
What do you mean by generic client? Can you repurpose bits of https://github.com/web-push-libs/web-push/blob/master/src/cli.js?

**Comment by gauntface** [comment]
What is wrong with the current api for sending web push?

**Comment by Black-Star** [comment]
Nothing wrong. 
A class based implementation will help us write a bit cleaner code and also to create one options and re use them.

For example:
  If i create  a class: 
         - I can have single options object and re use them across ( You know less objects in memory)

**Comment by marco-c** [comment]
I don't see a huge difference, you already need to call `setGCMAPIKey` just once and then `sendNotification` once per endpoint.
You don't need to create new objects for options either, you can just define the options once.

```
webPush.setGCMAPIKey('Your GCM API Key');
let options = YOUR_OPTIONS_HERE;

for (...) {
  sendNotification(..., ..., options);
}
```
