### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#242]
@PaulLewis was just trying out web-push and one thing that would have helped him would be to have a way to get what would be sent to the push service without actually making the request.

We currently only expose the encrypt method.

Would be good to expose the getVAPIDHeaders() and also expose a method generateRequestDetails() that returns the headers, endpoint and body that would other be used to make the final network request.

@marco-c what do you think of this?

**Comment by marco-c** [comment]
Makes sense, it can also help other people who are working on libraries for other languages (they can compare their output to ours to check if their implementation is working correctly).

**Comment by gauntface** [comment]
+1 to that.
