### ISSUE TITLE
Remove no longer needed old standard from http_ece

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#246]
See https://github.com/martinthomson/encrypted-content-encoding/issues/23.

**Comment by sudhirsaharan** [comment]
Hey Marco , can i pick up this issue for my mozilla contribution?

**Comment by marco-c** [comment]
@sudhirsaharan sure. The actual issue is at https://github.com/web-push-libs/encrypted-content-encoding/issues/23.

**Comment by sudhirsaharan** [comment]
@marco-c   For solving this bug , can i directly clone the web-push-libs repository and then remove the old content in ece.js and commit on a new branch or do i have to follow some other process . It's my first time , i'm unsure about the process . I hope you don't mind telling me.

**Comment by marco-c** [comment]
@sudhirsaharan you will have to clone https://github.com/web-push-libs/encrypted-content-encoding, make the fix there and submit a PR there.

**Comment by marco-c** [comment]
Thanks! This is now done upstream!
