### ISSUE TITLE
Question: bulk sending with payload impossible?

### ISSUE THREAD

**Issue by spock123** [web-push-libs/web-push#247]
Hi, I realize this might not be the right forum, as it is not necessarily something this library can do anything about - I just wanted to hear if you guys ran into the same issue as me, and if so, how you solved it:

The introduction of payload encryption using keys unique to each client, imho makes it practically unusable in a real world environment with thousands of subscribers.

Individual encryption makes make bulk notifications impossible. This means that if you have 50.000 subscribers, you'll have to send 50.000 http requests, instead or bundling 1000 at a time (as you can with native push notifications). 

Sending 50.000 http requests is practically impossible.

Does this really mean that web push with payloads are practically impossible?

Cheers guys - and thanks for a great module.

**Comment by gauntface** [comment]
Yes that is a restriction for web push encryption. You need to encrypt the payload for each individual user.

The reason behind this is that the browser can use any push service, meaning you the developer or the user may not trust the owner of the push service. The only way to secure that data is to encrypt it so the push service can't read the content.

I appreciate where you are coming from (I used to be a native app developer for all major platforms) but it's the reality of web push at least for the time being.

**Comment by spock123** [comment]
Thanks, appreciate it.
Cheers
