### ISSUE TITLE
Issue with TTL

### ISSUE THREAD

**Issue by surajwy** [web-push-libs/web-push#248]
Hi,

I tried searching google for TTL options for GCM. Everywhere I have got a simple way in which we need to specify a post param with time_to_live key in it. Nowhere I have found usage of TTL. Can you please give me some reference of it. 
Using TTL in headers is not working for me for chrome devices.

Thanks

**Comment by marco-c** [comment]
The TTL option in this library only applies to the Web Push standard services (so the Firefox one and FCM in Chrome).

We could probably support it in GCM as well, not sure if it's worth it (you could easily use FCM instead).

**Comment by gauntface** [comment]
https://tools.ietf.org/html/draft-ietf-webpush-protocol-12#section-5.2
