### ISSUE TITLE
npm install web-push --save Error

### ISSUE THREAD

**Issue by NathanHeffley** [web-push-libs/web-push#265]
I am trying to install the web-push NPM package, and receive the error "Refusing to install web-push as a dependency of itself"

I can successfully install other NPM packages such as Express, but web-push fails.

Attached is the npm-debug.log:

[npm-debug.log.txt](https://github.com/web-push-libs/web-push/files/764323/npm-debug.log.txt)

**Comment by marco-c** [comment]
Did you manage to find the culprit?

**Comment by NathanHeffley** [comment]
Nope, it just worked the next time I tried. Same computer, too. I had Internet connection but maybe there was something flukey going on between me and the package manager site.

**Comment by hao345813616** [comment]
@marco-c i have the same problem,pls help!
