### ISSUE TITLE
Remove requirement for `auth` parameter to send-notification, as it is not a supported subscription key.

### ISSUE THREAD

**Issue by hronik1** [web-push-libs/web-push#275]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

*Operating System*: OS X
*Node Version*: 7.7.2
*web-push Version*: 1.0.0

- [ ] Chrome
- [X] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

# Problem

According to the docs at https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/getKey, the only valid pushSubscription key is `'p256dh'`, however, `web-push send-notification` expects both `--key` and `--auth` params when providing a `--payload`.

The exact error is:
```Error sending push message:
Error: To send a message with a payload, the subscription must have 'auth' and 'p256dh' keys.
    at Object.WebPushLib.generateRequestDetails (/usr/local/lib/node_modules/web-push/src/web-push-lib.js:101:15)
    at Object.WebPushLib.sendNotification (/usr/local/lib/node_modules/web-push/src/web-push-lib.js:250:29)
    at sendNotification (/usr/local/lib/node_modules/web-push/src/cli.js:92:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-push/src/cli.js:112:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

# Expected

I am expecting a notification to be sent with a payload using just the `pd256dh` key from the subscription and not needing to provide an `auth` key.

# Features Used

- [ ] VAPID Support
- [ ] GCM API Key
- [X] Sending with Payload

# Example / Reproduce Case

`web-push send-notification --endpoint="<endpoint>" --key="<p256dh key>" --vapid-pvtkey="<pvt key>" --vapid-pubkey="<public key>" --payload="<payload>"`

# Other

**Comment by kitcambridge** [comment]
Whoops, looks like the docs are out of date. Both `p256dh` and `auth` are supported as of Firefox 45, and required for the new crypto scheme. IIRC, Chrome always required `p256dh` with `auth`, too.

**Comment by hronik1** [comment]
Thanks, I was testing on Firefox 44, because it looked like Push and Service workers were disabled in Firefox 45 and 52 Extended Support Releases. I will look for a later version and confirm. Thanks again.

**Comment by marco-c** [comment]
Closing, as I'm pretty sure things are working correctly with Firefox >= 45.
