### ISSUE TITLE
Safari and Edge support

### ISSUE THREAD

**Issue by kapoorji** [web-push-libs/web-push#276]
Hi Team,

Just wanted to know the support of Safari and Edge is in the pipeline or not?

**Comment by froodian** [comment]
Safari push is its own world, core contributors to this repo will have to answer that one.

I can say though for Edge that it's not supported in the browser yet: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/pushapi/

**Comment by marco-c** [comment]
This library is specifically for supporting the Web Push protocol, so Safari will not be supported.

We will make sure the library is compatible with Edge, once they support the Web Push API.

**Comment by kapoorji** [comment]
Yes, Edge support is on the way for Push, so safari only I need to handle separately.
Thanks for the update @marco-c @froodian

**Comment by maheshbale-wingify** [comment]
Has Edge support been added, now?

**Comment by marco-c** [comment]
Edge should be supported since https://github.com/web-push-libs/web-push/pull/309. @aliams can you confirm? We should update the `Browser Support` section in the README.

**Comment by aliams** [comment]
Yes, Edge supports web push now (as of the April 2018 update to Windows). I built a demo based on the web push library here: https://webpushdemo.azurewebsites.net/

**Comment by maheshbale-wingify** [comment]
Thanks marco and aliams.
@aliams : i went through the demo at https://webpushdemo.azurewebsites.net/. Could you give info on whats the notification payload format which works for edge browser notifications?

**Comment by aliams** [comment]
Edge supports both aesgcm and aes128gcm.

**Comment by maheshbale-wingify** [comment]
@aliams: what i meant is, what's the payload object structure for Edge notifications. Is it similar to chrome or Firefox or completely different?

**Comment by aliams** [comment]
It should be the exact same so that the same code would work interoperably across the different browsers.
