### ISSUE TITLE
command line error: UnauthorizedRegistration

### ISSUE THREAD

**Issue by zhuyingda** [web-push-libs/web-push#277]
I install the web-push package with global mode, and try this command and params:

web-push send-notification 
--endpoint=https://fcm.googleapis.com/fcm/send/c6c_iaSWVs8:APA91bF1Hmc6IOOti8uPoHFeuPfJv4K_UL6gSXLYfml_w2TzC7fHX271Yt6DNnC0f_EAUzs5Vy-0ZdZX6q46fXWl7J83andAumJLAT57tQWgChMf9lJSsdwDckVEpo5nPDxu-aGjed85 --key=BJKnNrohqVGZVeamR7dS9aQigz20pr-AoBkpgyQ2DUyPsGu4kwJeBsUQO7PvKPjJSogBBs5C2i1L2FEE-YhxBlg= --auth=kWnlzAGa22OaHFBqZRlSJw== --payload=helloworld --gcm-api-key=AAAA9di5kYw:APA91bHpMmKH2voljZkjcyRp08ijHnpslnmsdDQ4u8D93QlHQDbXLfYbIe4DzTluY3LYxUHcSmXQ2hIMFzaR5f6sucBhGf70sN1xwgp-AHIMTMnIqpqjONadfcVpyHegQX1igLi_q-MQ

but I got this Error:

```
Error sending push message:
{ [WebPushError: Received unexpected response code]
  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 400,
  headers:
   { 'content-type': 'text/html; charset=UTF-8',
     date: 'Fri, 14 Apr 2017 08:53:32 GMT',
     expires: 'Fri, 14 Apr 2017 08:53:32 GMT',
     'cache-control': 'private, max-age=0',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '1; mode=block',
     server: 'GSE',
     'alt-svc': 'quic=":443"; ma=2592000; v="37,36,35"',
     'accept-ranges': 'none',
     vary: 'Accept-Encoding',
     connection: 'close' },
  body: '<HTML>\n<HEAD>\n<TITLE>UnauthorizedRegistration</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>UnauthorizedRegistration</H1>\n<H2>Error 400</H2>\n</BODY>\n</HTML>\n',
  endpoint: 'https://fcm.googleapis.com/fcm/send/c6c_iaSWVs8:APA91bF1Hmc6IOOti8uPoHFeuPfJv4K_UL6gSXLYfml_w2TzC7fHX271Yt6DNnC0f_EAUzs5Vy-0ZdZX6q46fXWl7J83andAumJLAT57tQWgChMf9lJSsdwDckVEpo5nPDxu-aGjed85' }
```

**Comment by zhuyingda** [comment]
my website push url is:
https://www.zhuyingda.com/push

**Comment by gauntface** [comment]
FCM painfully uses this error for a range of errors.

Can you try this in Firefox and see if you get a more helpful error message.

**Comment by mselevan** [comment]
@gauntface i am hitting the same error, but not just on command line. FCM always seems to be returning this error, but firefox works fine

**Comment by zhuyingda** [comment]
It seems like the server key set error. I set the public key in this page https://web-push-codelab.appspot.com  and the FCM works fine. The problem solved.

**Comment by marco-c** [comment]
@mselevan please open a new issue if the problem wasn't the same as @zhuyingda's one.

**Comment by mselevan** [comment]
@zhuyingda I've tried using that site in the past but the private key throws an invalid key exception in py-vapid. What do I need to do to get this set of public/private keys to work with the py-vapid library?

**Comment by zhuyingda** [comment]
@mselevan I have not used py-vapid library, maybe your lib has any method to get this set of public/private keys. If you use this site, you dont need any lib, you just put the public key in your client side js, and push message on this site GUI. You can see my site: https://www.zhuyingda.com/push , the push.js and  sw.js.
