### ISSUE TITLE
ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by Gopinath478** [web-push-libs/web-push#281]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: <Windows >
*Node Version*: <4.2 | 6.0 | ...>
*web-push Version*: <1.0.0>

> Please select any browsers that you are experiencing problems with:

- [x] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem

Iam trying to send the push notification using the node js component, using the below command line, the subscription details are from my local, but the node js is giving error sending push message: ECONNREFUSED: 127.0.0.1:443.

web-push send-notification --endpoint='https://fcm.googleapis.com/fcm/send' [--key='d_KFmelrEaU:APA91bH4ymupN_bo4_lh1IUe8P1JJiaeHAe9aFagVGt70YYEhjiU41gn_if6murrFiCT7MXBl1qQvl-iPK02IbTTvsEeoO2os0jpn3Zh1CyALpj3RZNEjHNfQ0ATydASFcn4YgYXn3sF'] [--auth='Gj6jjSGZK2S4sFubM49G0Q=='] [--payload='text message here'] [--ttl='1000'] [--vapid-subject='mailto: example@web-push-node.org'] [--vapid-pubkey='BDS3J5jZL0fijt1vUhmjvusWHZ3LMFng1MU5hE4fs5Iur76f1zmDQOS2B8T68-8_5XIUOe05HtNroizOPrcFfFs'] [--vapid-pvtkey='WpNsFFOAdehUOBWH5wh4TmW7LqUsfFyVZn7tZbmMRLw'] 

# Expected

> I should get the push notification on my browser.

**Comment by marco-c** [comment]
The command shouldn't include the `[` and `]` parentheses. Are you sure the URL is correct?

**Comment by gauntface** [comment]
The URL isn't correct, it's missing the end of the subscription endpoint.
