### ISSUE TITLE
use web-push in  angularjs

### ISSUE THREAD

**Issue by narendrasinghrathore** [web-push-libs/web-push#283]
How i can get catch push event in angularjs, when it send web-notification to browser. 
Any demo/example/code sample.

Thank you.

**Comment by marco-c** [comment]
This library is for the server side and is framework agnostic.

**Comment by narendrasinghrathore** [comment]
How i can listen to push event on client side, on web-socket ?
@marco-c

**Comment by gauntface** [comment]
@narendrasinghrathore this library is server side, it simply sends the push message from from the server to a device.

In the browser (on the device) the push event will be passed to your service worker. For high level explanation see: https://web-push-book.gauntface.com/chapter-01/02-how-push-works/
