### ISSUE TITLE
Build using Babel

### ISSUE THREAD

**Issue by abdulhannanali** [web-push-libs/web-push#288]
Why isn't web-push project using babel to build all the files for better backwards compatibility?

**Comment by gauntface** [comment]
What version of node do you want to run on? If it's less than 4, why support a version that isn't supported by Node themselves?

**Comment by marco-c** [comment]
Agreed, we shouldn't support those old versions.

**Comment by abdulhannanali** [comment]
Sounds cool!

**Comment by abdulhannanali** [comment]
@marco-c Don't you want to accept PR that use `async/await` functions and other cool es6 constructs while being compatible even with node4 without that `--harmony` flag.

**Comment by marco-c** [comment]
If it makes sense to use features not supported on Node 4, then yes, but I think we should do it only if really needed, not just for the sake of it.

**Comment by gauntface** [comment]
:+1: I'm extremely happy that we can test on supported node versions without messing with a build step.

I would be very much in favor of gradual PR's moving to classes, let and const etc, assuming they are supported in Node 4+/

**Comment by abdulhannanali** [comment]
@gauntface Yeah es6 classes are awesome
