### ISSUE TITLE
Cannot find module 'ecdsa-sig-formatter'

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#290]
# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: Linux
*Node Version*: 8.1.4
*web-push Version*: 3.2.2

> Please select any browsers that you are experiencing problems with:

- [X] Chrome
- [X] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

# Problem

When attempting to use web-push to send a notification I get the following error:

Error: Cannot find module 'ecdsa-sig-formatter'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/matt/Projects/Code/presentations/2017/sfhtml5/node-app/node_modules/jwa/index.js:5:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

If I manually install the module it's missing everything starts to work.

# Features Used

- [X] VAPID Support
- [ ] GCM API Key
- [X] Sending with Payload

# Example / Reproduce Case

```javascript
const webpush = require('web-push');
const subscriptionModel = require('./models/subscription-models');

const PUBLIC_SERVER_KEY = 'BGrhvwvoOoslJ1GeqtUgLDX1cKwnZeHHwkbriRoH_qC07VpUKDNy3jVYCD-M21qXJ7uUNGvEDkhbA4d07gMH5nA';
const PRIVATE_SERVER_KEY = 'OUWzPNJ_osn5AUh1t8c6rTXobx4LjHQymzyTAkkn4Mo';

webpush.setVapidDetails(
  'mailto:matt@gauntface.co.uk',
  PUBLIC_SERVER_KEY,
  PRIVATE_SERVER_KEY
);

return subscriptionModel.getSubscriptions()
.then((subscriptions) => {
  console.log(subscriptions);

  return subscriptions.reduce((promiseChain, subscription) => {
    return webpush.sendNotification(subscription, 'Hello SFHTML5.');
  }, Promise.resolve());
});
```

**Comment by marco-c** [comment]
The dependency is coming from [node-jwa](https://github.com/brianloveswords/node-jwa).
The only change I see in the latest jwa version is https://github.com/brianloveswords/node-jwa/commit/07542feea1645c35928e73ec89f392dcd1932dbb.

So, ecdsa-sig-formatter should be automatically installed when installing jwa, not sure why it's not being installed.

**Comment by gauntface** [comment]
Will close this as it should have installed - let's blame NPM and it's package.lock.json for now.
