### ISSUE TITLE
Sending Push notifications to browser

### ISSUE THREAD

**Issue by jonalxh** [web-push-libs/web-push#291]
Hi, I'm trying to user your library but I couldn't find how to send a push notification from browser to browser, is to say,  I've a local application using FCM, if I send a message from Push webs or cURL it works, but in your library there is not a space to specify the receiver token.
Here is a cURL example 

```
curl -X POST -H "Authorization: key=AAAAs...xLil2KPz" -H "Content-Type: application/json" -d '{
  "notification": {
    "title": "¡Buenos días!",
    "body": "Ésta es una prueba",
    "icon": "firebase-logo.png",
    "click_action": "http://localhost:8081"
  },
  "to": "eB9M2Yx9u...6xrJeieA9hSPzWIkml39s_vfaNzVa_WxL"
}' "https://fcm.googleapis.com/fcm/send"
```

I wanna know how to "translate" or "convert" the above code with your library.

Could you help me please?

**Comment by gauntface** [comment]
This is an FCM request NOT a web push request.

Please look for an FCM library to send the message (or make a POST request from a script / server language of your choice).
