### ISSUE TITLE
Failed to translate Buffer to a EC_POINT

### ISSUE THREAD

**Issue by come25136** [web-push-libs/web-push#292]
> web-push v3.2.2

```Error: Failed to translate Buffer to a EC_POINT``` will occur if you delete the service worker stored in the browser

How can I solve it?

**Comment by gauntface** [comment]
@come25136 Could you provide some more thorough reproduction steps.

**Comment by come25136** [comment]
@gauntface 

I am well aware that I can not send a push notification when deleting a service worker.

This problem occurs when **only** the service worker is deleted.

If you remove or block service workers and notification privileges from the browser, 410 and endpoints are returned, but if only the service worker is deleted, ```buffer could not be converted to EC_POINT``` will be returned.

How to reproduce
After confirming that you can receive Web Push in the browser, delete **only** the service worker
Then I will send the Web Push again

This environment
Vivaldi 1.11.917.43 (Stable channel) (32-bit)
Android 7.0.0 Chrome 61.0.3163.81

Finally, I am Japanese, I am not good at English.
This English translation uses Google Translate.
If you feel that reading is difficult, I'm sorry.

**Comment by gauntface** [comment]
@come25136 could yo uplease provide use with an example of your web-push code just to be sure we are reproducing the same way?

**Comment by come25136** [comment]
```javascript
const
    webpush = require('web-push'),
    payload = JSON.stringify({
        title: 'title',
        body: 'body',
        icon: 'icon.png',
        url: 'https://example.com'
    }),
    subscription = {
        endpoint: 'https://fcm.googleapis.com/fcm/send/hoge',
        keys: {
            auth: 'hoge_aaa',
            p256dh: 'hoge_bbb'
        }
    }

webpush.setVapidDetails('hoge@example.com', 'hoge_public', 'hoge_private');

webpush.sendNotification(subscription, payload)
    .catch(res => {
        if (res.statusCode === 410) {
            console.log('410');
        } else {
            console.error(res);
        }
});
```

The part using hoge uses my information.

**Comment by lfreneda** [comment]
It turned out that it was a wrong formatted subscriptions D:

**Comment by come25136** [comment]
@lfreneda Sorry for the late reply, it has not been settled yet.

However, since I have not used this library for several years, I would like to close the issue.
