### ISSUE TITLE
Push Notifications Doesn't Show Up

### ISSUE THREAD

**Issue by antoaravinth** [web-push-libs/web-push#297]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup
 
> Please provide the following details, the more info you can provide the
> better.

*Operating System*: OSx
*Node Version*: v6.10.2
*web-push Version*: 3.2.4

> Please select any browsers that you are experiencing problems with:

- [x] Chrome
- [x] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem

> Push notification doesn't show up

# Expected

> Push notification should show up

# Features Used

- [x] VAPID Support
- [ ] GCM API Key
- [x] Sending with Payload

# Example / Reproduce Case

I'm using the client code in react (along with service worker) which is shown below here:

```
  var endpoint;
  var key;
  var authSecret;

  // We need to convert the VAPID key to a base64 string when we subscribe
  function urlBase64ToUint8Array(base64String) {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding)
      .replace(/\-/g, '+')
      .replace(/_/g, '/');

    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);

    for (let i = 0; i < rawData.length; ++i) {
      outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
  }

  function determineAppServerKey() {
    var vapidPublicKey = 'BJZWuHMx8wVbUa-YxUGsDCRc2iB2i5TvRN4QYXqVCk0lQWxdqaX0iY1MFX-Ze97TizsE8s6NNlEZtZC2GxoiNzo';
    return urlBase64ToUint8Array(vapidPublicKey);
  }

export default function registerServiceWorker() {
	if('serviceWorker' in navigator) {
		navigator.serviceWorker.register(`${process.env.PUBLIC_URL}\sw.js`).then(function(register){
			console.log("worked", register)
        return register.pushManager.getSubscription()
          .then(function(subscription) {

              if (subscription) {
                // We already have a subscription, let's not add them again
                return;
              }

              return register.pushManager.subscribe({
                  userVisibleOnly: true,
                  applicationServerKey: determineAppServerKey()
                })
                .then(function(subscription) {

                  var rawKey = subscription.getKey ? subscription.getKey('p256dh') : '';
                  key = rawKey ? btoa(String.fromCharCode.apply(null, new Uint8Array(rawKey))) : '';
                  var rawAuthSecret = subscription.getKey ? subscription.getKey('auth') : '';
                  authSecret = rawAuthSecret ?
                    btoa(String.fromCharCode.apply(null, new Uint8Array(rawAuthSecret))) : '';

                  endpoint = subscription.endpoint;
                  alert("came here")
                  return fetch('http://localhost:3111/register', {
                    method: 'post',
                    headers: new Headers({
                      'content-type': 'application/json'
                    }),
                    body: JSON.stringify({
                      endpoint: subscription.endpoint,
                      key: key,
                      authSecret: authSecret,
                    }),
                  })

                });
            });
		}).catch(function(err){
			console.log("Error",err)
		})
	}
}
```

Note that I have generated the VAPID keys from `generateVAPIDKeys` function. Now the code runs on port `3000` for the web-push, I run an express server, whose code is:

```
const webpush = require('web-push');
const express = require('express');
var bodyParser = require('body-parser');
var path = require('path');
const cors = require('cors');
const app = express();
app.use(cors());
app.options('*', cors());


// Express setup
app.use(express.static('public'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({     // to support URL-encoded bodies
  extended: true
}));

function saveRegistrationDetails(endpoint, key, authSecret) {
  // Save the users details in a DB
}

console.log(webpush.generateVAPIDKeys())

webpush.setVapidDetails(
  'mailto:example@yourdomain.org',
  'BJZWuHMx8wVbUa-YxUGsDCRc2iB2i5TvRN4QYXqVCk0lQWxdqaX0iY1MFX-Ze97TizsE8s6NNlEZtZC2GxoiNzo',
  'cC3Trh3r6fsWKrnJybaZoGSHx_Z3xxcg8vltghaoZaQ'
);

// Home page
app.get('/', function (req, res) {
  res.sendFile(path.join(__dirname + '/index.html'));
});

// Article page
app.get('/article', function (req, res) {
  res.sendFile(path.join(__dirname + '/article.html'));
});
// Register the user
app.post('/register', function (req, res) {

  var endpoint = req.body.endpoint;
  var authSecret = req.body.authSecret;
  var key = req.body.key;

  // Store the users registration details
  saveRegistrationDetails(endpoint, key, authSecret);

  const pushSubscription = {
    endpoint: req.body.endpoint,
    keys: {
      auth: authSecret,
      p256dh: key
    }
  };

  var body = 'Thank you for registering';
  var iconUrl = 'https://raw.githubusercontent.com/deanhume/progressive-web-apps-book/master/chapter-6/push-notifications/public/images/homescreen.png';

  webpush.sendNotification(pushSubscription,
    JSON.stringify({
      msg: body,
      url: 'https://localhost:3000/',
      icon: iconUrl,
      type: 'register'
    }))
    .then(result => {
      console.log("came here ")
      console.log(result);
      res.sendStatus(201);
    })
    .catch(err => {
      console.log(err);
    });

});

// The server
app.listen(3111, function () {
  console.log('Example app listening on port 3111!')
});
```

This runs on port `3111`. When I open up `3000` port, I could able to see the Push Notification "Allow/Block" pop up comes up (both in chrome and as well in firefox). Here comes the problem, web-push notification (`Thank you for registering`) message doesn't come! Inspecting in the network tab shows no error as call to `register` clearly shows up `201` code. 

There are no errors on front end and in express side as well. 

I'm not sure whether this is an issue or i'm missing something here.

# Other

NOTE: If same code which runs on port `3000` is moved to `3111`, then everything works perfectly!

**Comment by subversivo58** [comment]
In your Service Worker example I see the record but I do not see the listener ... are you listening to the notification event?


    self.addEventListener('push', function(event) {
        console.log('[Service Worker] Push Received.');
        /**
          Assuming the payload string is a valid JSON and can be parsed and contains a minimum of valid
          fields... possible fields can be:
          title: String,
          body: String,
          icon: String,
          badge: String,
          image: String,
          vibrate: Array,
          sound: String,
          dir: String,
          tag: String,
          requireInteraction: Boolean,
          renotify: Boolean,
          silent: Boolean,
          timestamp: Date
        */
        let data = JSON.parse(event.data.text());
        // show
        event.waitUntil(self.registration.showNotification(data.title, data));
    });



I think this question is an implementation error and not necessarily an error in this lib. Maybe a [Web Push Book](https://web-push-book.gauntface.com/) can help you.

**Comment by marco-c** [comment]
Could you show us your service worker source?

Have you tested this in Firefox too? Are you experiencing the problem only in Chrome (you only selected Chrome as affected) or in both?

**Comment by antoaravinth** [comment]
@subversivo58: Oops silly mistake. Looks like I have added the listener but still my browser was using old service worker code(some caching issues). Now everything works perfectly,. 

@marco-c: Its working, my bad. Thanks, will close it.
