### ISSUE TITLE
install web-push fail

### ISSUE THREAD

**Issue by hao345813616** [web-push-libs/web-push#298]
Refusing to install web-push as a dependency of itself
pls help!
logs:
verbose stack Error: Refusing to install web-push as a dependency of itself
43 verbose stack     at checkSelf (D:\wanghao\tools\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (D:\wanghao\tools\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (D:\wanghao\tools\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (D:\wanghao\tools\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at D:\wanghao\tools\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at D:\wanghao\tools\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at D:\wanghao\tools\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap

**Comment by marco-c** [comment]
Can you show us your package.json? Can you try installing web-push again?

**Comment by marco-c** [comment]
Closing for lack of response.
