### ISSUE TITLE
push failed with large number of message  

### ISSUE THREAD

**Issue by nguyenvinh1612** [web-push-libs/web-push#305]
# Setup
installed node.js on windows 8, tested on chrome
https://nodejs.org/en/download/

# Problem
with a single endpoint, the push worked 
when I increased the number of messages sent to a single endpoint (I created a loop to send the same message to an endpoint ) , the push failed.
with 1000 message, there was an error with socket hang up 
with the 400k message, there was an error with heap up memory 

# Expected
Don't get those error when deploying it on production server (Linux environment)

# Features Used
Sending with Payload

# Example / Reproduce Case
```javascript
const payload = '{"title":"your push title","content":"have a nice day.","url":"https://yoururl.net","imgUrl":"img/wpush/icon.png?v=1","tag":"1","isRequireInteraction":"true"}';

for(var i = 0; i < 1000; i++)
{
	  webPush.sendNotification(subscription,payload);
	  console.log("done" + i);
}
};
```

# Other
see attached images 
![error2](https://user-images.githubusercontent.com/12492344/34346773-c7f79e78-ea2d-11e7-8f75-42d35c51f713.jpg)
![socket](https://user-images.githubusercontent.com/12492344/34346774-c824c092-ea2d-11e7-9f57-d9906d4c91d1.jpg)

**Comment by marco-c** [comment]
I think it's the caller's responsibility to throttle the requests.
