### ISSUE TITLE
Not working on chrome localhost(Not secure)

### ISSUE THREAD

**Issue by rravithejareddy** [web-push-libs/web-push#306]
![screenshot 77](https://user-images.githubusercontent.com/29831966/34883063-76b08ed0-f7de-11e7-9915-4bf915854a42.png)
I tried on https://serviceworke.rs/ site  push notification are coming in chrome, but when i downloaded and running on localhost it's not working on chrome.

**Comment by marco-c** [comment]
Already replied to you on https://github.com/mozilla/serviceworker-cookbook/issues/289#issuecomment-357226808.
serviceworke.rs is not using the latest version of this library and is not using VAPID, so you'll probably need to set a GCM API key.

**Comment by rravithejareddy** [comment]
It's not working even after  GCMapikey included, you already know that latest GCM need refreshtoken in message body everytime.
