### ISSUE TITLE
It's not working even after GCMapi key included

### ISSUE THREAD

**Issue by rravithejareddy** [web-push-libs/web-push#307]
when i tried uisng fcm i need to to include registrationtoken in messagebody, it worked.
![screenshot 78](https://user-images.githubusercontent.com/29831966/34903410-df2f5bf8-f856-11e7-966f-9adc6d352c18.png)
 do i need to use registrationtoekn in webpush to work on chrome.

**Comment by marco-c** [comment]
Hello @rravithejareddy. This is a separate project, please keep the discussion on https://github.com/mozilla/serviceworker-cookbook/issues/289#issuecomment-357226808.
