### ISSUE TITLE
Sending notifications via WebSockets

### ISSUE THREAD

**Issue by lewispham** [web-push-libs/web-push#308]
WebPush is using http protocol for sending notifications. I think it'll be more efficient to send notifications via WebSockets instead.

**Comment by MartijnDwars** [comment]
Why do you think WebSockets are more efficient than HTTP? From my point of view, WebSockets solve a different problems (bi-directional communication, low latency) which are not relevant for Web Push.

**Comment by gauntface** [comment]
https://web-push-book.gauntface.com/chapter-07/01-faq/#why-is-this-any-better-than-web-sockets

**Comment by lewispham** [comment]
Agree with @gauntface . I forgot that ServiceWorker has a temporary lifetime so websocket connections can not persist within ServiceWorker. I'm closing this issue since my suggestion seems not possible.
