### ISSUE TITLE
Setup code coverage collection

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#311]

**Comment by feugy** [comment]
Hello @marco-c !
Coverage with istanbul is already included.
Is this bug about sending it to some 3rd party service such as [coveralls](http://coveralls.io/) or [codecov](https://codecov.io/)?

**Comment by marco-c** [comment]
Yes, it was added with #58. Now we want to actually make use it and so send the data to one of those services.

**Comment by collierrgbsitisfise** [comment]
@marco-c  could i receive more details ?

**Comment by marco-c** [comment]
@collierrgbsitisfise sure, what do you want to know?

**Comment by collierrgbsitisfise** [comment]
@marco-c where i can find more details how to deploy project locally ?

**Comment by marco-c** [comment]
@collierrgbsitisfise this is mostly a standard node.js project, so you can just run `npm test` to run tests (if this is what you are asking).

**Comment by ruchikabgosain** [comment]
hello, is this issue still open?

**Comment by marco-c** [comment]
@ruchikabgosain yep, we still need to do this!

**Comment by ruchikabgosain** [comment]
HEY @marco-c ! Can I know what changes are to be made exactly? I'm new to this repo and would love some help :)

**Comment by marco-c** [comment]
This issue is actually pretty self-contained and generic (you don't need to know the code of this repo much). You'll need to read the documentation of codecov (or coveralls) and see how to enable uploading the code coverage data we collect to those services.

**Comment by collierrgbsitisfise** [comment]
@marco-c , i add additional step in CI(upload coverage to coveralls), could you please instruct me how correctly create PR for this issue ?
