### ISSUE TITLE
About browser support matrix

### ISSUE THREAD

**Issue by dmdwns67** [web-push-libs/web-push#315]
Hello! 
I'm a student trying to make a push service system with VAPID, not using 'gcm_sender_id'.
According to the browser support matrix in README, my system cannot work in Opera and Samsung Internet Browser as I didn't use gcm_sender_id. But, it works well when I tested on my mobile phone. 
Why does it work? I used Opera with v44.1.2246 and Samsung with v6.2.01.

**Comment by marco-c** [comment]
It should work with new versions of Opera and Samsung. See the discussion in https://github.com/web-push-libs/web-push/issues/125#issuecomment-360746319.
