### ISSUE TITLE
Notification properties (actions,image) not working. 

### ISSUE THREAD

**Issue by gsoy** [web-push-libs/web-push#316]
# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: <Linux | Windows | OS X>
*Node Version*: <4.2 | 6.0 | ...>
*web-push Version*: <1.0.0>

> Please select any browsers that you are experiencing problems with:
- [* ] Chrome - 64.0.3282.167
- [* ] Firefox Developer Edition

# Problem
> notification is not working with image, actions.

# Expected
> Shown notification must be include image and action parameters. 

# Features Used
- [ ] VAPID Support
- [* ] GCM API Key
- [* ] Sending with Payload

**Comment by marco-c** [comment]
This doesn't depend on the serverside part of web-push, but on your service worker implementation.
