### ISSUE TITLE
WebPush - Node - Loop issues

### ISSUE THREAD

**Issue by kuladeep18** [web-push-libs/web-push#321]
Hi Sending 10,000 push in a single loop using webpush.sendnotification....

* Loop stops at 1000 subscribers and no error is thrown

Tried below option with promises but it is taking 30 mins for 10k subscribers which is not the right way

Also 2500 subscriber tokens are marked as invalid (410) by FCM which to me looks very surprising. I believe there might be something wrong with the code

Vapid Details Public key is the same for every subscriber but private key differs for each subscriber

exports.sendPwaPushNotifications = function (subscriptions, params) {
    // console.log("subscriptionsData ", subscriptionsData.length)
    // var deferred = Q.defer();
    let promiseChain = Promise.resolve();
    var options, ClickURL, deepLinkURL;
    var dataToSend = {
        message: params.message,
        // clickTarget: ClickURL,
        title: params.title,
        image: params.mobileImage ? params.mobileImage : params.webImage,
        showActionButtons: params.isCTA,
        buttons: params.buttons // Buttons is a arrray: structure - [{title:'Like', action:1, icon:'iconURL', actionURL:'XXX'},{title:'Share', action:2, icon:'iconURL', actionURL:'XXX'}]
        // TTL: 3600
    };
    if (params.eventId) {
        dataToSend.eventId = params.eventId;
        params.campaign_name = "EVENT_" + params.eventId;
        params.deepLinkURL = params.pwa_deeplink_url;
    }
    let subscription;
    for (let i = 0; i < subscriptions.length; i++) {
        // subscription = subscriptions[i];
        promiseChain = promiseChain.then(() => {
            return triggerPushMsg(subscriptions[i], dataToSend, options, params);
        });
    }

    return promiseChain;

}

const triggerPushMsg = function (subscription, dataToSend, options, body) {
    // console.log(subscription)
    subscription.endpoint = subscription.DeviceID;

    if (body.eventId) {
        dataToSend.clickTarget = body.deepLinkURL;
    } else {
        deepLinkURL = body.deepLinkURL;
        ClickURL = JUNE_URL + "/api/notifications/count?redirect_url=" + deepLinkURL + "&member=" + subscription._id + "&cname=" + body.campaign_name;
        dataToSend.clickTarget = ClickURL;
    }

    if (body.buttons) {
        _.map(body.buttons, function (button) {
            button.actionURL = JUNE_URL + "/api/notifications/count?redirect_url=" + button.clickURL + "&member=" + subscription._id + "&user_action=" + button.action + "&cname=" + body.campaign_name;
        });
    }

    options = {
        vapidDetails: subscription.vapidDetails
    }
    // delete subscription.DeviceID;
    return webPush.sendNotification(subscription, JSON.stringify(dataToSend), options)
        .catch((err) => {

            handleErrorNotification(subscription, dataToSend, err, body);
            if (err.statusCode === 410) {
                return deleteDeviceID(subscription._id, subscription.appKey);
            } else {
                console.log('Subscription is no longer valid: ', err);
            }
        }).then((successCb) => {
            if (successCb && successCb.statusCode === 201) {

                handleSuccessNotification(subscription, body);
            }
            else {
                console.log("Subscription error ", subscription._id)
            }
        })

};

**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: <Linux | Windows | OS X>
*Node Version*: <4.2 | 6.0 | ...>
*web-push Version*: <1.0.0>

> Please select any browsers that you are experiencing problems with:

- [ ] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem

> Please explain what behaviour you are seeing.

# Expected

> Please explain what you expected to happen

# Features Used

- [ ] VAPID Support
- [ ] GCM API Key
- [ ] Sending with Payload

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

# Other

> Please put any remaining notes here.

**Comment by marco-c** [comment]
I think you will have to throttle the requests to avoid problems.
