### ISSUE TITLE
im a starter of  web-push. I got read ECONNRESET

### ISSUE THREAD

**Issue by xuzhanhh** [web-push-libs/web-push#324]
i successfully use https://web-push-codelab.glitch.me/ to notification a message.  But while i download its source code and run it. it will log an error message read ECONNRESET.

here is the server code.
` 
 webpush.sendNotification(
    req.body.subscription,
    req.body.data,
    options
  )
  .then(() => {
    res.status(200).send({success: true});
  })
  .catch((err) => {
    if (err.statusCode) {
      res.status(err.statusCode).send(err.body);
    } else {
      res.status(400).send(err.message);
    }
  });
`

**Comment by xuzhanhh** [comment]
<img width="1101" alt="wx20180507-155241 2x" src="https://user-images.githubusercontent.com/20735181/39691114-0a2257cc-520f-11e8-914b-8bd1eaf675d6.png">

**Comment by xuzhanhh** [comment]
should i set the GCM API key in back end ?

**Comment by marco-c** [comment]
This sounds unrelated to this library, maybe you have configured something wrong in the project you have downloaded.
