### ISSUE TITLE
what is browser key ? how to generate browser key?

### ISSUE THREAD

**Issue by anlexN** [web-push-libs/web-push#325]
web-push command usage:
>   web-push send-notification --endpoint=<url> [--key=<browser key>] [--auth=<auth secret>] [--payload=<message>] [--encoding=<aesgcm | aes128gcm>] [--ttl=<seconds>] [--vapid-subject=<vapid subject>] [--vapid-pubkey=<public key url base64>] [--vapid-pvtkey=<private key url base64>] [--gcm-api-key=<api key>]

README don't tell anything about browser key!

**Comment by marco-c** [comment]
It's the `p256dh` key from the push subscription.

**Comment by anlexN** [comment]
please update your document. thank you.
