### ISSUE TITLE
Not Working With Mobile Browser

### ISSUE THREAD

**Issue by gaurav-bothra** [web-push-libs/web-push#327]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: Windows 10
*Node Version*: v8.9.0
*web-push Version*: 3.3.1

> Please select any browsers that you are experiencing problems with:
- All Android Browser

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem

> Push Notification is not working in Mobile Browser
- [ ] Sending with Payload

**Comment by marco-c** [comment]
`All Android Browser`, in which browsers have you tested?

Do you see any error message from `web-push` when you send the notification?

**Comment by gaurav-bothra** [comment]
In mobile or in console?
In console there is no error

**Comment by gaurav-bothra** [comment]
I tested in Chrome & Firefox

**Comment by marco-c** [comment]
> In mobile or in console?
> In console there is no error

How are you sending the notification? Are you using the web-push CLI interface?

If there's no error returned by `web-push` or the push service, this is probably a bug in your client service worker code.

**Comment by gaurav-bothra** [comment]
i am sending notification using express app

**Comment by marco-c** [comment]
Pretty sure this is not an issue in the lib.
