### ISSUE TITLE
Can't send notification with error: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by quanghd96** [web-push-libs/web-push#331]
I am trying send notification by method: webpush.sendNotification(pushSubscription, "Your Push Payload Text",options).catch(err => console.log(err));
But:
Failed to load https://fcm.googleapis.com/fcm/send/dddahCFPhZk:APA91bHAymLXYkAtVXiGLjDnQJzjgHE8tKybo2Xq9MD1HoLM_jbQ-hAYsPmBYpIxw1hfxP7SXvnasukkNbrQKEQg7ZG_StWYwf7nFh8ypv7odZ9jS_7iHgXmUDp5vQIiEeeioDMhqV7Y: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by marco-c** [comment]
The library is meant to be used on the server-side.

**Comment by AymenRouis** [comment]
Sorry for posting this comment in a closed issue.

I'am trying to use web-push library in a salesforce commerce cloud project, and the problem is that I can not use this library in the backend, I only have the ability to use it in frontend.

So do we have any workaround to avoid the No 'Access-Control-Allow-Origin' error ?

Thanks a lot

**Comment by marco-c** [comment]
@AymenRouis what is the point of sending a push notification from the frontend itself? Push notifications are useful to notify a user of some event while they are not on your site, but if they are already on your site...

**Comment by AymenRouis** [comment]
@marco-c thank you for your response.

In SFCC the backend controller can render an Html page as a response, and inside this Html page I can put the script which contains the web-push library.
So the users are not really on my site.

The idea is like this: 
Job ==> controller ==> HTML as response ==> script inside the Html ==> web push send notification inside the script.

**Comment by marco-c** [comment]
@AymenRouis I'm not so familiar with SFCC, is there no backend component?
