### ISSUE TITLE
we can not receive push message because we are in china?

### ISSUE THREAD

**Issue by anlexN** [web-push-libs/web-push#346]
can google chrome update "https://fcm.googleapis.com" to accessible endpoint in china? Even, we browser can not use pushmanager to get subscription. In server, we can use proxy to web-push. but in client, we not.

**Comment by marco-c** [comment]
@anlexN unfortunately this is outside of our control, you should contact the Google Chrome developers.

**Comment by anlexN** [comment]
@marco-c , can you recommand me how to do? i make a issue on [google chrome](https://github.com/googlechrome), but they don't reply me.

**Comment by marco-c** [comment]
You can try from https://bugs.chromium.org/p/chromium/issues/list. Honestly, I'm not sure the problem is easily fixable for them.

**Comment by Hotcapsicum** [comment]
I find this issue just now, and now is 2020, chrome still can't receive push message . It took me a month to figure it out
