### ISSUE TITLE
Type Error: ascii is not a function

### ISSUE THREAD

**Issue by der74er** [web-push-libs/web-push#355]
# Setup

> Please provide the following details, the more info you can provide the
> better.

Web-push is on a Linux Box based on BananaPi. 
Ubuntu 16.04 with Kernel 3.4.112, Apache 2.4.18, Node JS Version 4.2.6 and Web-Push 3.3.2

> Please select any browsers that you are experiencing problems with:

- [X] Chrome 67
- [X] Firefox 60.0.2

Browsers run on a Win10 Box

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem
Hi, i tried to make a web-push server after the instructions from c't Magazine, see also Details on 
[](https://ct.de/yy3m ). The Backend worked fine and created a call for web-push. The operating Mode was vapid Mode. I turned on the rights to get Push Messages and subscribed the browser.

But after Copy&Pate into SSH console i just got  the Error Type Error: ascii is not a function
I don't know what ist the Problem.

# Expected

I expected to get a Push message on the browser.

# Features Used

- [X] VAPID Support
- [ ] GCM API Key
- [X] Sending with Payload 

# Example / Reproduce Case

web-push send-notification --endpoint=https://updates.push.services.mozilla.com/wpush/v2/gAAAAABbNxyuthYG84devhQAuMgadi1Ud5dv-HUm6KgyuFv_Iy1dbW_ybQD9_R6HL9eYh8E5dEDiQV0CGnuAcp2xIkTQdU6fJvoqvV2SUWS6pHNIwCk0J3zmeHf7yqTxgf4WIPi6nskycTf0oJ5J5lmQT-Zt067u9MyeuzL1aSY5mXh8GXlH9sk --key=BK5k5lzPGBC5rWhGrEyJv7xkkFuRYUUWiy3BdugtiHW5pmJbCVeQ6kTmZiQ05bQvRlplmBGeJI8dz0Djrybre5c --auth=T3uKEnLMXYnLk9ZZIsPhQQ --vapid-pubkey=BJzVE_Et1aQJsMDKzvAD6beIsR0A6We_yUMhFuzIqNI-JUKYvhZ60q8-NYM2Herh1OF9XrQ8BpH__7z1ORxVCmU --vapid-pvtkey=1S4PQHDaLa2xYAJsajZSKapUbI_ptYT08BOkm-15lCo --vapid-subject=mailto:wortwart@woerter.de --ttl=300 --payload="Test"

# Other

Don't worry about the Keys, i generate new ones when the Problem is fixed...

**Comment by der74er** [comment]
Sure. here it is. I tested it an got a different error this time:
[Error: The subscription endpoint must be a string with a valid URL.]
Generated with Firefox 61.0 - i made a new Push Subscription as second try but this doesn't help.

https://updates.push.services.mozilla.com/wpush/v2/gAAAAABbRtHzMoc6_LkzUxaLlK7Ntfhl5XwIzsgX6lRVOWEfuSMLCPtDpPPO-zJqE0e3DrKvj9wCVMw4Jv2gkonJybfhKWX8WHzkAqnrnTJ_Jycf9DQOhFL8L--ihIEL41iinwtNRgFHx65Wi1SUX9loIeTnf6Ha1yTvI34xEnKVQByw3WpDhno

**Comment by marco-c** [comment]
It worked here, the output was "Push message sent.".

**Comment by der74er** [comment]
Okay, so it  is not the Command. But where can i search for the Problem. Maybe a missing dependency?

**Comment by marco-c** [comment]
Is there a stack trace or "TypeError: ascii is not a function" is the only output?

What version of Node.js are you using?

**Comment by der74er** [comment]
No just the error, no stack trace message. I use Node.Js 4.2.6

**Comment by marco-c** [comment]
There might be something unsupported with Node.js 4, it is a very old version no longer maintained (https://twitter.com/nodejs/status/968177367033229315). We're still running tests with Node.js 4 and they are passing, but we're not testing *everything* so there might be something broken.

I suggest you update to a newer version of Node.js (4 could have security vulnerabilities). If you can't, please try to write a JS script to send the notification and run it instead of running the CLI directly, so maybe we get a more useful stack trace.

**Comment by der74er** [comment]
Hello Marco, this was the right direction! Thank you very much!
I suggested my fresh installed NodeJS need to be the right version, but my Distro shipped an old one. 
After installing V8.x  the Push Message could be send. I'm very happy!
