### ISSUE TITLE
encoding option in cli is put into wrong option slot

### ISSUE THREAD

**Issue by lodott** [web-push-libs/web-push#358]
When the --encoding option is used via cli, the following error occurs:

Error: 'encodingType' is an invalid option. The valid options are ['headers', 'gcmAPIKey', 'vapidDetails', 'TTL', 'contentEncoding', 'proxy'].
 
Replacing
    options.encodingType = args.encoding;
in cli.js#95 with
    options.contentType = args.encoding;
fixes this issue.

**Comment by marco-c** [comment]
Fixed by #359.
