### ISSUE TITLE
"self signed certificate in certificate chain" error on sendNotification method

### ISSUE THREAD

**Issue by helen3308** [web-push-libs/web-push#360]
I'm running node as back end server. Got "self signed certificate in certificate chain" error when call  webpush.sendNotification method. Please advice what to do to solve the problem

![certificate error](https://user-images.githubusercontent.com/31115167/42594343-cbae1152-8503-11e8-9f26-af09554b779d.png)

**Comment by marco-c** [comment]
Are you behind a firewall of some sort?

**Comment by helen3308** [comment]
Thanks marco-c, it's working after I add the following line
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"
