### ISSUE TITLE
subscribe to we push notification question

### ISSUE THREAD

**Issue by pantchox** [web-push-libs/web-push#362]
Hi,

I have more a technical question.

How can i from server side, subscribe to a web push for example of cnn.com or any other website that offers web push notifications services.

thanks.

**Comment by marco-c** [comment]
There's no generic way to implement what you want, as each website will implement the subscription mechanism in its own way.
You could implement it controlling a browser via a script (e.g. via Selenium), but the implementation would be different for each website (and it would also be difficult to maintain, as sites can change).

**Comment by marco-c** [comment]
(I'm closing the issue because what you request is outside the scope of this library)

**Comment by pantchox** [comment]
thanks i will try to do it with puppeteer.
