### ISSUE TITLE
How to use web-push in angular service

### ISSUE THREAD

**Issue by helen3308** [web-push-libs/web-push#368]
I'm able to have the example up and running with node server. But my project is angular 6 & web.api, I wonder if web-push can be used in angular 6 service as well because we don't have node server.

I tried to use it in angular service, got the error when build. 

const webpush = require("web-push");
webpush.sendNotification(
           sub,
           JSON.stringify(notificationPayload)
 );

[exec] [0m[1m[33mWARNING in ./node_modules/web-push/node_modules/asn1.js/lib/asn1/api.js[39m[22m[0m
[exec] [0m[1m[33mModule not found: Error: Can't resolve 'vm' in './node_modules\web-push\node_modules\asn1.js\lib\asn1'
 
If web-push can only be used for node, could anybody recommend a solution for sendNotification in angular service?

**Comment by BibAnu** [comment]
Hi, @helen3308 

If you haven't still found the answer. You need @angular/service-worker to receive push notification.
First subscribe to push notification from your angular app and send it to nodejs server, then using web-push you may send push notification to your angular app.

Here's the [step-by-step guide](https://blog.angular-university.io/angular-push-notifications/) for it, hope it helps you.
