### ISSUE TITLE
problem with pushNotification data to use later

### ISSUE THREAD

**Issue by MINASHIJ** [web-push-libs/web-push#372]
hi, i,m going too use this library to notify users, so I need to send a notification for special user, I saved subscription data consist of endpint, and keys : p256dh, auth.
when I need to send notification, I give the sendNotification function the subsribtion data. but it did not work.
what should i do? please help me.

**Comment by marco-c** [comment]
Hello @MINASHIJ, I suggest following one of the Web Push tutorials online (many explain how to use this library).
