### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by masihfathi** [web-push-libs/web-push#374]
Is there a business admin panel or project? something like : https://onesignal.com 
Or do you have idea for develop something like that? 
tnx

**Comment by debashishkumar** [comment]
Yes I worked with pushengage.com
Thanks and Regards
Debashish Kumar
Contact:- +91-8269973626

**Comment by marco-c** [comment]
It is outside the scope of this library. This library is only implementing the server-side Web Push protocol.
