### ISSUE TITLE
Some General Question: On which cases subscriber endpoint address get change?

### ISSUE THREAD

**Issue by OmriY** [web-push-libs/web-push#387]
I have a large amount of subscribers that I can't send them push message,
because their **browser decided to change their endpoint address** (Mostly users subscribed from chrome browser on Android, but it happened on Mozilla Firefox for Android also)

I have tried to listen to **'pushsubscriptionchange'** event in the service worker JS file,
but I didn't succeed to debug and trigger it, no matter what (tried cancel subscription, tried to clear browser cache etc...).

so my question will be:
**on which kind of situations the browser decided to change subscriber endpoint address? 
and what can I do to prevent this lose of subscriber and get his new endpoint, even if he didn't come back to my site for a very long time ?**

**Comment by marco-c** [comment]
See the following StackOverflow questions:
https://stackoverflow.com/questions/48507092/does-pushsubscription-endpoint-change-over-time
https://stackoverflow.com/questions/36602136/how-can-i-test-pushsubscriptionchange-event-handling-code
https://stackoverflow.com/questions/35645628/how-to-test-pushsubscriptionchange-within-a-service-worker
