### ISSUE TITLE
setVapidDetails first argument

### ISSUE THREAD

**Issue by exebook** [web-push-libs/web-push#396]
What is the meaning of the first argument to `setVapidDetails()`? Is this just an arbitraty string?

**Comment by gauntface** [comment]
Taken from https://web-push-book.gauntface.com/chapter-04/02-web-push-protocol/

> Finally, the `sub` value needs to be either a URL or a mailto email address. This is so that if a push service needed to reach out to sender, it can find contact info from the JWT. (This is why the web-push library needed an email address).

(Sub == the subject in this context)
