### ISSUE TITLE
Update eslint-config-airbnb

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#405]
After updating eslint-config-airbnb we have many linting errors. We should fix them and update the eslint configuration at the same time.

**Comment by marco-c** [comment]
See https://github.com/web-push-libs/web-push/pull/380, which is the automated PR showing the failure to update.

**Comment by marco-c** [comment]
Have you forked the repository?

**Comment by rub1e** [comment]
Apologies @marco-c - I had a bit of a shocker, managed to overwrite all of my changes :scream: 

PR is #417
