### ISSUE TITLE
UC Browser 

### ISSUE THREAD

**Issue by SeregaSE** [web-push-libs/web-push#409]
# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*:  OS X
*Node Version*: 11.0.0
*web-push Version*: 3.3.3

> Please select any browsers that you are experiencing problems with:

- [ ] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
-  UC Browser Mobile (12.9)

# Problem

I'am trying to send push to UC browser mobile on Android

Response from webpush
```
{ statusCode: 201,
  body:
   '{"message":"Created. The request to send a push message was received and accepted.","code":201}',
  headers:
   { date: 'Thu, 24 Jan 2019 16:59:58 GMT',
     'content-type': 'application/json',
     'transfer-encoding': 'chunked',
     connection: 'close' } }
```

But push undelivered

# Expected

Push delivering

# Features Used

-  VAPID Support
- [ ] GCM API Key
-  Sending with Payload

# Example / Reproduce Case
```js
const send = (subscription, message) => new Promise((resolve, reject) => {
    webPush.sendNotification(subscription, JSON.stringify({ title: 'Ping', body: 'Pong' }), {
        contentEncoding: 'aesgcm',
    })
        .then(function (request) {
            console.log('REQUEST');
            console.log(request);
            // console.log('Push Application Server - Notification sent to');
            resolve([null, 'ok']);
        }).catch(function (err) {
            console.log(err);
            // console.log('ERROR in sending Notification, endpoint removed');
            resolve([err])
        });
});
```

# Other 
My code works for me in Chrome. I think it's not a webpush problem, but mb someone faced UC Browser...

**Comment by marco-c** [comment]
Have you figured it out?

Pretty sure it's not a problem in this lib.

**Comment by SeregaSE** [comment]
Yeap, i think the problem is in UC Browser webpush subscription server. Sometimes server subscribed you with fcm api endpoint, sometimes with us endpoint server. If it is fcm api, webpush works.

After uc browser update started to work. 12.x.x version
