### ISSUE TITLE
Inconsistency in failure rate

### ISSUE THREAD

**Issue by anilkumargautam** [web-push-libs/web-push#424]
Hi

I am sending chrome push notification in bulk using 

async.eachLimit(payload.registrationIds, 100,
    function (row, callback) { 
                    webpush.sendNotification(row.key, message, options){}
}

is there any limit to send notification per second/minute/hour/day ? As when i try high number of registration id than failure rate is high but ok with less number of registration id.

Please help me or let me know if more information requires

Thanks

**Comment by marco-c** [comment]
There might be limits imposed by the service, but they are outside our control.
