### ISSUE TITLE
Web push sending problem to gcm endpoint.

### ISSUE THREAD

**Issue by nozkok** [web-push-libs/web-push#426]
We use the https://github.com/web-push-libs/web-push package. We divide all tokens into groups of 1000 and send web push by sending a post request to GCM for each token with foreach loop. The system is working smoothly for about two years. But the response timeles have been prolonged on the GCM side for about 1 month. As a result of the detailed debuging, the encryption (AuthToken and p256PH) and sending GCM request processes are completed in 3 seconds for all 1000 tokens. But their responces are coming late from GCM side. Therefore, the pushing time has increased and we are experiencing timeout problems.
  Is there any kind of problem that you encountered and solved?

**Comment by marco-c** [comment]
I'm not aware of any problem. CC @gauntface
