### ISSUE TITLE
Not working in Chrome with localhost

### ISSUE THREAD

**Issue by Shifs** [web-push-libs/web-push#439]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: Linux
*Node Version*:10.8.0
*web-push Version*:3.2.5

> Please select any browsers that you are experiencing problems with:

- [x] Chrome

> Please list the browsers you are have tested this, including the version
> of the browser (Chrome  Firefox c).

# Problem

> Please explain what behaviour you are seeing.

I am integrating Webpush with Angular & Node following 
https://blog.angular-university.io/angular-push-notifications/ . I am able to get push notifications in Firefox but in chrome I am not getting anything.

**Comment by MartijnDwars** [comment]
Did you try the following?

> Note: Unregister any service workers and clear all service worker caches for localhost so that they do not interfere with the lab. In Chrome DevTools, you can achieve this by clicking Clear site data from the Clear storage section of the Application tab.

Source: https://developers.google.com/web/ilt/pwa/lab-integrating-web-push

**Comment by Shifs** [comment]
@MartijnDwars Tried this as well still it is not working . Notification payload in backend is 
 const notificationPayload = {
        "notification": {
            "title": "Angular News",
            "body": "Newsletter Available!",
            "icon": "assets/main-page-logo-small-hat.png",
            "vibrate": [100, 50, 100],
            "data": {
                "dateOfArrival": Date.now(),
                "primaryKey": 1
            },
            "actions": [{
                "action": "explore",
                "title": "Go to the site"
            }]
        }
    };

**Comment by marco-c** [comment]
This is likely not an issue with the library, but with your code.

**Comment by Shifs** [comment]
@marco-c The issue was with localhost in Linux OS . When tried the same in other OS , it worked .Also in Linux system , when I virtually hosted it , it started working
