### ISSUE TITLE
Proxy accepts only url string

### ISSUE THREAD

**Issue by tim-kuteev** [web-push-libs/web-push#450]
# Setup

*Operating System*: Windows
*Node Version*: 8.12
*web-push Version*: 3.3.3

# Problem

Proxy option accepts only strings (web-push-lib.js:170) but not [HttpsProxyAgent options](https://github.com/TooTallNate/node-https-proxy-agent#new-httpsproxyagentobject-options)

# Expected

I expect it to accept either options object as a proxy parameter:
```javascript
const urlParse = require('url').parse;

const proxyOptions = urlParse('http://myproxy');
proxyOptions.rejectUnauthorized = false;

webPush.sendNotification(subscription, payload, {
  proxy: proxyOptions,
});
```

or HttpsProxyAgent as an agent parameter

```javascript
const HttpsProxyAgent = require('https-proxy-agent');
const urlParse = require('url').parse;

const proxyOptions = urlParse('http://myproxy');
const agent = new HttpsProxyAgent(proxyOptions);

webPush.sendNotification(subscription, payload, {
  agent: agent,
});
```

**Comment by marco-c** [comment]
This sounds good to me, care to submit a PR?

**Comment by tim-kuteev** [comment]
@marco-c I would, but I don't think I have access rights to create a brunch :)

**Comment by marco-c** [comment]
@tim-kuteev you don't need access to this repository in order to create a branch. You can fork the repository, create a branch in your fork, then submit a PR to this repository from your fork.
