### ISSUE TITLE
403 FCM Errors | Vapid key Pair Incorrect 

### ISSUE THREAD

**Issue by renegadeHomie** [web-push-libs/web-push#462]
*Operating System*: Linux
*Node Version*: 8.4.0
*web-push Version*: 3.3.5

> Please select any browsers that you are experiencing problems with:

- [ - ] Chrome
- [ - ] Firefox

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).
Chrome Stable,
Chrome Canary
Firefox Stable

# Problem

In a strangely astonishing scenario, the vapid key pair generated by the web-push module is not working fine for me.

I am getting 403 from FCM when trying to send push. 

A. I am using the vapidPublicKey to generate the subscription on the browser level using the following code : 
`serviceWorkerRegistration.pushManager.subscribe({
                    userVisibleOnly: true,
                    applicationServerKey: util.urlBase64ToUint8Array(vapidPublicKey)
                })`

B. Then using both the keys to send push using webpush node library.

C. The vapid keys are as follows : 
     publicKey : 'BHo-JIY76o86oMsdGYCMbcsGYJWbbp_59XpfwpcGOVlkWUV3Odwp7mpXdYg4a-Ehg0sutM9zLCHIoxR67vnZkAg'
     privateKey : 'PQ0qHHxqHq7aiKX22fI4GwDmZ9GQpl7DL0ZFesAY9wA'

# Expected

> This is highly shocking as all my previously generated keys work fine, just this above-mentioned pair is causing me pain.

# Features Used

- [ - ] VAPID Support
- [ - ] Sending with Payload

Looking for more context on this and if anyone else is also facing this abnormality!

**Comment by renegadeHomie** [comment]
The Error response looks like this : 
`{ Error
    at IncomingMessage.<anonymous> (/Users/renegade/WebEngage/Push-Notifications/node_modules/web-push/src/web-push-lib.js:316:20)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 403,
  headers: 
   { 'content-type': 'text/plain; charset=utf-8',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '1; mode=block',
     date: 'Tue, 28 May 2019 08:37:11 GMT',
     'content-length': '21',
     'alt-svc': 'quic=":443"; ma=2592000; v="46,44,43,39"',
     connection: 'close' },
  body: 'invalid JWT provided\n',
  endpoint: 'https://fcm.googleapis.com/fcm/send/e8apgUBKL1s:APA91bHer3Oie57tG9c_ORamszynnUZE-OCJRoEs4xIyaKO7L-lI0jxMldixWaEf54J2fH6IieAG-lbSW1OcsXr4sptD3EddLW73Qs8U2ec2Rzg-H9PBVHzc4VBB5_JWaSC0ejE8G3fP' }`

**Comment by cbratschi** [comment]
See https://github.com/web-push-libs/web-push/issues/457. I have the same issue.
