### ISSUE TITLE
 TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by shravan-saini** [web-push-libs/web-push#474]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: Windows
*Node Version*: 4.2.1
*web-push Version*: latest (3.3.5)

> Please select any browsers that you are experiencing problems with:

I am not experiencing any problem in browser

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem
I am trying to push notification to the browsers  from node server.
I am using node version 4.2.1
and I am getting an error in the webpush.sendNotification() function.

The error is :: TypeError: this is not a typed array.

you may refer to the code sample given below.

# Expected

> Please explain what you expected to happen

# Features Used
I am using  VAPID Support. 
- [x] VAPID Support

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

# Other

> Please put any remaining notes here.
```
         const vapidKeys = {
        publicKey:'BE3JY2e2jLBUwDqTvrhDaB222RAb1FG-jPkaty- 
          DQwdjN0mWUUbQVrSvqk8BUNdLI22lXwuDGN-nd-zqVksxtrA',
        privateKey: '4tYLQ1mt6s922HLwP9x773V8hmbcqiTp21u6biOpGdw'
      };
      
    webpush.setVapidDetails(
          'mailto:tech@qdesq.com',
           vapidKeys.publicKey,
           vapidKeys.privateKey
    );

var dataToSend = {
        notification:{
            title:notificationdata.title,
            body:notificationdata.body,
            redirectUrl:notificationdata.redirectUrl,
            icon:"qdesq.com"
        }
    }

        var pushConfig = {
                 endpoint: subscription.subscription.endpoint,
                 keys: subscription.subscription.keys
             }

          var StringDataToSend = JSON.stringify(dataToSend);
             
             webpush.sendNotification(pushConfig, StringDataToSend)
             .then(function(res){
                 console.log('res',res);
                 loop(i+1);
             })
             .catch(function(err) {
                 console.log('errrrrrrrrrrr---',err); /// **Here I am getting error: This is not Typed array**
                 if (err.statusCode === 404 || err.statusCode === 410) {
                     console.log('Subscription has expired or is no longer valid: ', err);
                
                 } else {
                     throw err;
                 }
                
             });
```

**Comment by marco-c** [comment]
Please provide all parameters (`notificationdata`, `subscription`) so it's easier to reproduce for me.
