### ISSUE TITLE
TypeError: Failed to fetch when i want send notification

### ISSUE THREAD

**Issue by hamyarwoo** [web-push-libs/web-push#477]
when i want to send notification with web-push
in first my code is 
`webpush.setVapidDetails(
                                'mailto: iranimij@gmail.com', "BBnpssqQeDV4toU2tDlc9taOX_MgTriCHJ5TP-Hn7Fg5CngjWHrT6M4_HQXprFl97CqmaLqYrMR1Kc-f4Ju****",
                                "g2a6TM_oJgU9xSMRnLyQ1IkGpWegWT5sJxnh2yb****"
                            );`

then i create my pushSubscription constant like this 

`const pushSubscription = {
    endpoint: "https://fcm_googleapis_com/fcm/send/c2ZPknFAD78:APA91bFLg1v6IQTIVRFCiRf5wfxtHJeHB1sFMu4ZufsPXlhSfPLefP1XRWkpv3HJOnHxzRpPbEIG_HI8wX8mX3H5Chr1Fj4_VBxfvq3nNqz6ereppYxZ-moTvx35ndzzmgS1TG9EGNAb",
    keys: {
        auth: "hvP5JljkjWEnHvvtPG****",
        p256dh: "BNx7knu59gw5r_6-Ym36VOjJu86LWb1YTbN4ntWOfMpTc-mO1wZ0P7BQC3Z5t2CnRgguwGuqs-5oZnhWCAA****"
    }
};`

and then i call send notification function

`webpush.sendNotification(pushSubscription, JSON.stringify("sdsd")
).catch(function(e){
    console.log(e);
});`

but in response i get in console
![ax](https://user-images.githubusercontent.com/47588564/61168279-b4c89b00-a560-11e9-9c21-b487b4364ec9.jpg)

:

The FetchEvent for "https://fcm_googleapis_com/fcm/send/c2ZPknFAD78:APA91bFLg1v6IQTIVRFCiRf5wfxtHJeHB1sFMu4ZufsPXlhSfPLefP1XRWkpv3HJOnHxzRpPbEIG_HI8wX8mX3H5Chr1Fj4_VBxfvq3nNqz6ereppYxZ-moTvx35ndzzmgS1TG9EGNAb" resulted in a network error response: an object that was not a Response was passed to respondWith().
Promise.then (async)
(anonymous) @ service-worker.js:96
app-main.js:431 TypeError: Failed to fetch

**Comment by marco-c** [comment]
This is a problem in your service worker code, not with the library. As you can see, your browser did receive the push message.

**Comment by hamyarwoo** [comment]
my browser didn't receive any push message ,

**Comment by hamyarwoo** [comment]
you see that my error at line 431 , file : app-main.js
this is exactly is my send notification method

**Comment by marco-c** [comment]
Are you trying to use the library in the browser itself?
