### ISSUE TITLE
response of sendnotification is promise status rejected 

### ISSUE THREAD

**Issue by hamyarwoo** [web-push-libs/web-push#478]
out put of send notification method is :
Promise {<pending>}
__proto__: Promise
[[PromiseStatus]]: "rejected"
[[PromiseValue]]: TypeError: Failed to fetch

**Comment by marco-c** [comment]
What is the code you are using to send the push notification?

**Comment by hamyarwoo** [comment]
i solve this issue
my notification url was destroyed when i want to send notification
