### ISSUE TITLE
"Unregistration request sent" in Chrome resulting in 403 errors

### ISSUE THREAD

**Issue by craig-gordon** [web-push-libs/web-push#523]
# Setup

*Operating System*: Windows 7 Ultimate SP1
*Node Version*: 10.16.3
*web-push Version*: 3.4.1

# Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

# Tested With

Chrome 77.0.3865.120 (Official Build) (64-bit)
Firefox 70.0 (64-bit)

# Problem

I am having problems sending notifications (with sendNotification) using Chrome. Notifications process and display correctly in Firefox.

Registering a service worker and creating a push subscription work fine. The first notification I send results in a 201 response from the FCM endpoint, but my service worker does not intercept the request and no push notification is displayed. All further notification requests for the given subscription result in a 403 error, with message "invalid push subscription endpoint.\n". After a lot of digging, I eventually found in Chrome's GCM Internals page that the sendNotification requests were triggering "Unregistration requests", which is why the first notification request results in a 201 and all further requests result in 403s. See image for more details.

![](https://puu.sh/EzolF/ee15054f68.png)

# Expected

I expect sendNotification to trigger a push notification just as it does in Firefox, not to unsubscribe the endpoint.

# Features Used

- [X] VAPID Support
- [ ] GCM API Key
- [X] Sending with Payload

# Example / Reproduce Case

Frontend code:

```
navigator.serviceWorker.register("ServiceWorker.js");

    navigator.serviceWorker.ready
      .then(registration => {
        return Promise.all([
          registration,
          registration.pushManager.getSubscription()
        ]);
      })
      .then(([registration, existingSubscription]) => {
        if (existingSubscription) return existingSubscription;

        const vapidPublicKey =
          "BJMQ-CpMM_-OoO2hNPt3oM_pM8TSpPhSL_xGwGix99iLj0hdyHCZTP3XYeOO8sf9ghhHHFO2I7QpDrgSyGd1VQ4";
        const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey);

        return registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: convertedVapidKey
        });
      })
```

Server code:

```
const webPushService = require("web-push");

webPushService.setVapidDetails(
  "https://catchthe.run/",
  "BJMQ-CpMM_-OoO2hNPt3oM_pM8TSpPhSL_xGwGix99iLj0hdyHCZTP3XYeOO8sf9ghhHHFO2I7QpDrgSyGd1VQ4",
  "S_3sQfZvYAh7LGuKkXreV_kfcmAkdMFL0nAoI2z1P3w"
);

server.get("/push", (req, res) => {
  webPushService
    .sendNotification(
      JSON.parse(
        '{"endpoint":"https://fcm.googleapis.com/fcm/send/c1PfFz7qN9w:APA91bEOnOrhTI4k-femQNkugIEvnd6AToy7RuK3FlQgXWfvtfBRJ-gi1jxdf4hR1oRjMRrjneuf4ulA7WlMglghrfpbHEOJcByfXgz77NTh1Ru_5KD_bDZ8Yuc6SCx-Lm_c9-kTq7aZ","expirationTime":null,"keys":{"p256dh":"BDYgLFJP0AI4rpV9nBB0a1XRZGlHT5ELUF4l_BsR7le9vH8oeKs4vn5QStAIEnyx9pJI7qmwYQ-X-qQ3yXDG5zA","auth":"Mf_Mc6lDfOlT-pfY7aZaxA"}}'
      ),
      "hi"
    )
    .then(res => console.log("webpush res:", res))
    .catch(err => console.log("webpush error:", err));
});
```

**Comment by marco-c** [comment]
This must be an error on your side, or Google's, as a simple example like this is working for basically every user of the library (and also, we have integration tests with Chromium which are working).

**Comment by marco-c** [comment]
I'd suggest trying on another machine and another website.

**Comment by mohamedhafez** [comment]
I've also been getting errors like this intermittently just from Google, just for a handful of users, and then it ends for those users and starts up for some others. This has only been going on for about a month. I think its a bug on Google's end since nothing has changed on my end in a while, but have no way of proving that or seeing if they are aware of it...
