### ISSUE TITLE
push unsubscribe?

### ISSUE THREAD

**Issue by IDONTSUDO** [web-push-libs/web-push#525]
Is there any way to unsubscribe users from push notifications?

I have users in the system, they can log in from different devices. I write data about these devices to the database. And as soon as an event appears in the system, I notify the user about this. I would not want to remove old push messages from the queue if they are read by the user on the same device.

Could you help me and answer how realizable this  is within your library?

**Comment by MartijnDwars** [comment]
> I would not want to remove old push messages from the queue if they are read by the user on the same device.

I don't fully understand what you mean by this. If you want to prevent a push message from showing up, you can change your service worker to query the state on theserver. If the server says that the notification is not relevant any more (because it has been handled by a different device?) you can discard the notification.

**Comment by IDONTSUDO** [comment]
Sorry for my English, I'm from Russia.


Well, can I sign several devices with the same key?

At the moment I am signing every new device. And I send data about them to the server. And at that moment when the event occurs, I send push notifications. For all of these recipients. And it turns out that when the user reads the push notification from 1 device and reads it. The notification itself remains unread on all other devices.



![fa5](https://user-images.githubusercontent.com/44754773/69011210-3f8b2d80-0979-11ea-998d-e927421da0a3.jpg)

**Comment by MartijnDwars** [comment]
> At the moment I sign every new device and send the data to the server. When an event occurs push-notifications are sent for all recepients.

When you create a subscription in the browser, you probably send the subscription to the server (see [Usage Example](https://github.com/web-push-libs/webpush-java/wiki/Usage-Example#client-side)). If your user is logged in to your application then you can send along some authentication token. That way you can connect all subscriptions to a single user.

> When user reads push-notification on one device, same notification remains unread on every other device

Note that you do not _need_ to show a push notification, your service worker can decide to discard it. For example, when the service worker receives a push notification, it can ask the server whether the user has already read the message on a different device. If not, you show the push message and update the server that you've shown the push message.

**Comment by IDONTSUDO** [comment]
thx!
