### ISSUE TITLE
Mobile Firefox: Not opening any windows onClick notification after the app is closed

### ISSUE THREAD

**Issue by nanda248** [web-push-libs/web-push#527]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: Windows 10 Enterprise
*Node Version*: 10.6
*web-push Version*: 3.4.0

> Please select any browsers that you are experiencing problems with:

- [ ] Chrome
- [*] Firefox Mobile
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem
On Chrome (mobile): After entirely closing the PWA and browser, the notifications are still coming and on clicking the notification also open the PWA or browser and takes the user to respective page.
On Firefox (mobile): After entirely closing the PWA and browser, the notifications are still coming and on clicking the notification does not open any PWA or browser. The notification was cleared. But it doesn't open anything.

The application is hosted in Windows IIS server (version 10)
The site is running in https with self-signed certificate. 
Tested on Android Mobile devices.

# Expected
Expect Firefox mobile to work like Chrome mobile. Is it Firefox browser limitation?

# Features Used

- [*] VAPID Support
- [*] GCM API Key
- [*] Sending with Payload

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

# Other

> Please put any remaining notes here.

**Comment by marco-c** [comment]
This seems like a bug in Firefox. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1602086.

**Comment by marco-c** [comment]
@nanda248 could you provide more details on https://bugzilla.mozilla.org/show_bug.cgi?id=1602086?
