### ISSUE TITLE
Very rarely VAPID keys do not work: 403 FCM (invalid JWT provided)

### ISSUE THREAD

**Issue by gbhrdt** [web-push-libs/web-push#532]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

*Operating System*: Linux
*Node Version*: 6.0
*web-push Version*: latest

- [x] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

# Problem

In some very special cases keys generated with `generateVAPIDKeys` are not working (at least with Chrome subscriptions).

Example, not working key pair:

pvt: `pT2ssKAhMQNkUSLcrbIJm4Hp5yads77GDhwUOoLphwA`
pub: `BCGMtGuI7QFGaWoBpiDoc-avJMwSH3BNU5R4kthBxoJV5NWdtwOl9cyrVBU5nBH4Q_94ODUGQwBI7GSAw-Kdgz0`

```
{ WebPushError: Received unexpected response code
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/web-push/src/web-push-lib.js:341:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 403,
  headers:
   { 'content-type': 'text/plain; charset=utf-8',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '0',
     date: 'Fri, 29 Nov 2019 14:27:52 GMT',
     'content-length': '21',
     'alt-svc':
      'quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000',
     connection: 'close' },
  body: 'invalid JWT provided\n',
  endpoint:
   'https://fcm.googleapis.com/fcm/send/xxxxxxxxxxx }
```

# Expected

The VAPID keys should be working.

# Features Used

- [x] VAPID Support
- [ ] GCM API Key
- [ ] Sending with Payload

# Example / Reproduce Case

Unfortunately we only ran into this problem once. We generated thousands of keys so far which have been working without any issues.

# Other

**Comment by gbhrdt** [comment]
We ran into another not working key paid.

Private Key: `bDUN37UjKJqTy7u4ebRPvkVR2RTjMA_nAyU9BFRWHwA`

The key also ends with `wA` maybe this is the root cause?

**Comment by silentjohnny** [comment]
The ending in wA is an indication of a null-padded bytestring at the end (the extra 0 will result in a base64 representation ending in 'A=') . We're also seeing issues with these keys, as null-padding should be skipped by the signing algorithms and as such should be padded as a prefix to the bytestring.

This would mean in the first case the private key hpT2ssKAhMQNkUSLcrbIJm4Hp5yads77GDhwUOoLphwA becomes AKU9rLCgITEDZFEi3K2yCZuB6ecmnbO-xg4cFDqC6Yc

In the second case, bDUN37UjKJqTy7u4ebRPvkVR2RTjMA_nAyU9BFRWHwA would become AGw1Dd-1Iyiak8u7uHm0T75FUdkU4zAP5wMlPQRUVh8


@gbhrdt can you give those a try (with the same public key and the same endpoints)?

I think the generateVAPIDKeys() method needs a change to pad the key buffer at the start instead of at the end.

If you can confirm these keys work for you I can make a PR.

**Comment by gbhrdt** [comment]
@silentjohnny  Wow, good find! The keys you sent me are working perfectly.
If you could make a PR this would be awesome!

**Comment by paulo-pertierra** [comment]
I know this is 2025 so I am sorry in advance, but just in case, necro-ing this thread, we found another invalid VAPID key generated by this package. 
Public Key: `BA5UV882c5Aj4BwAr92oGrJE1odyu2EWDxogsilz-wW4KBmTv7KEE8EaGHoLam8HcGILlR5Ts1pIyfKAZ6waODE`
Private Key: `uC3BelX3SKxUh9snvCUGDDYu5C3klGg614vJh2d-V4w`

```
Error sending push: WebPushError: Received unexpected response code
    at IncomingMessage.<anonymous> (/home/paulo/node_modules/web-push/src/web-push-lib.js:378:20)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  statusCode: 403,
  headers: {
    'content-security-policy-report-only': "script-src 'none'; form-action 'none'; frame-src 'none'; report-uri https://csp.withgoogle.com/csp/goa-520bfc14_2",
    'content-type': 'text/plain; charset=utf-8',
    'cross-origin-opener-policy': 'same-origin',
    vary: 'Sec-Fetch-Site, Sec-Fetch-Mode, Sec-Fetch-Dest',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '0',
    date: 'Wed, 26 Nov 2025 05:36:54 GMT',
    'content-length': '40',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'
  },
  body: 'permission denied: invalid JWT provided\n',
  endpoint: 'https://fcm.googleapis.com/fcm/send/cFbY8vMfg8Q:APA91bGh2-h8NjeuW3y28CZ5sHxhNoOkdLvqGnMRsDFl9N1hlcqJUSDo02opzziTOvF8LmXAR98v8HG9VevXiI5BJzM54UyTgh1w8lF9cpChnwE1KY66UHXA1p1fp2QAZYMPjeK1_32L'
}
```

Maybe this is an ultra-rare occurence, but still happens from time to time? Again, very sorry for necro-ing.
