### ISSUE TITLE
This package broke our Node app ... any advice on disabling its usage for certain browsers?

### ISSUE THREAD

**Issue by imkane** [web-push-libs/web-push#539]
I searched the documentation and issues, however I don't see any method for detecting a browser (like Safari or older versions of Edge) and not using this package.

Because now we have users trying to access our site, and all they see is a **blank page**. 

Console error:
> BroadcastChannel is not defined

I know the whole "buyer beware" motto, but you may want to put a huge disclaimer at the top saying something like:

### *** 25% of the world's browsers won't be able to access your app/site if you use this ***

**Comment by marco-c** [comment]
This package is a server-side component, so by definition it can't break web pages.

**Comment by marco-c** [comment]
Note: you are probably using some client-side library which uses BroadcastChannel.

**Comment by imkane** [comment]
@marco-c my apologies! You're correct, it's this frontend code that's causing the issue, not the web-push package:

>  const channel = new BroadcastChannel("sw-messages");
