### ISSUE TITLE
git: some versions tag missing

### ISSUE THREAD

**Issue by rinsuki** [web-push-libs/web-push#544]
v3.4.3 and v3.4.1 tag is missing in this git repository https://github.com/web-push-libs/web-push/tags (but released in npm).

can you add tag (and push) to repository?

**Comment by marco-c** [comment]
Thanks for reporting, I've just pushed v3.4.3.
Unfortunately I made a mistake for v3.4.1. I committed locally, then forgot to push, then merged some PRs, so the commit corresponding to the tag was never pushed. I have decided to remove it to avoid a mismatch between the tag on the repo and the code published on NPM.

**Comment by marco-c** [comment]
If you really need v3.4.1 let me know and maybe we can figure something out.
