### ISSUE TITLE
how to send notification to More than one user

### ISSUE THREAD

**Issue by vishalvanpariya** [web-push-libs/web-push#562]
Hello,

I am using this web-push module for send notification.
I can not send a notification to more than one user using one function.

```var sub =[];
    subscription={
        "endpoint": "1st endpoint",
        "keys": {
          "auth": "1st auth",
          "p256dh": "1st"
        }
      };
    var subscription2={
        "endpoint": "2nd user",
        "keys": {
            "p256dh": "2nd",
            "auth": "2nd auth"
        }
    }
    sub.push(subscription);
    sub.push(subscription2);
    
    webpush.sendNotification(sub,payload).catch(err=>console.error(err));
```
if I put one object its working fine but more than one user I am using loops.
so, please help me to send a notification to bulk users.

Thanks

Vishal

**Comment by marco-c** [comment]
Unfortunately it isn't possible (not just with this library, in general). See https://github.com/web-push-libs/web-push/issues/247.
