### ISSUE TITLE
DOMException: Registration failed - push service error

### ISSUE THREAD

**Issue by anamritraj** [web-push-libs/web-push#574]
# Setup

*Operating System*: Linux & OS X
*Node Version*: v12.13.1
*web-push Version*: ^3.4.3

> Please select any browsers that you are experiencing problems with:

- [x] Chrome for Android
- [x] Chrome Beta for Android
- [x] Firefox for Android
- [x] Brave Browser Android
- [ ] Chrome
- [ ] Firefox Developer Edition 
- [ ] ~Opera for Android~
- [ ] ~Samsung Internet Browser~
- [ ] Other

Crossed ones I didn't try.

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).
- [x] Chrome for Android (Chrome 81.0.40044.96, Android 10)
- [x] Chrome Beta for Android (Chrome 81.0.40044.96, Android 10)
- [x] Firefox for Android (68.7.0)
- [x] Brave Browser Android (Brave 1.5.131, Chromium 80.0.3987.162)
- [x] Chrome (Version 80.0.3987.162 (Official Build) (64-bit) Mac)
- [ ] Firefox Developer Edition (76.0b1 (64-bit))
- [ ] ~Opera for Android~
- [ ] ~Samsung Internet Browser~
- [ ] Other

Crossed ones I didn't try.

# Problem

> Please explain what behaviour you are seeing.

I have implemented push notifications on this site, https://livecovid.in.

It works on all the browsers(Firefox and Chrome) on my Mac. But when I try the same on my phone I am getting this error. On all browsers.

```
DOMException: Registration failed - push service error
```

Now at first I thought this was a problem with my website, I checked and re-cheked that the configuration was correct on the server and client side. I made sure private and public keys were correct. And they are. And this whole time the problem was only in the browsers on the phone.

So I tried this other demo website https://gauntface.github.io/simple-push-demo/ and the same error occured (on my phone). Then I tried this demo https://serviceworke.rs/push-payload_demo.html. 

Both demos worked fine on my Mac, but none of them worked in any of my phone browsers.

Now, at this point I asked one of my friends to try it and they seem to have no such issues on their phone in any browser, which was weird. Then I asked one of my other friends, and they had the same problem as me. 

# How to reproduce?

- Goto https://livecovid.in or https://gauntface.github.io/simple-push-demo/
- Click any row in the table and click on the little bell icon.
- It will prompt you for notifications, Click yes, approve the notification access.
- If it works for you you will see this.
<img width="431" alt="Screenshot 2020-04-13 at 10 31 37 AM" src="https://user-images.githubusercontent.com/11889942/79093461-feeddf80-7d71-11ea-9462-8ecaebfd07c6.png">

- Otherwise you will see something like this if it fails.
<img width="337" alt="Screenshot 2020-04-13 at 10 33 14 AM" src="https://user-images.githubusercontent.com/11889942/79093547-365c8c00-7d72-11ea-910e-a3b11c927384.png">

# Expected

> Please explain what you expected to happen
Everyone should be able to register for the notifications regardless of what device they are on.
# Features Used

- [x] VAPID Support
- [ ] GCM API Key
- [x] Sending with Payload

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

https://github.com/anamritraj/livecovid.in-webapp

https://github.com/anamritraj/livecovid.in-webapp/blob/master/src/services/subscription.service.js#L21-L64

# Other
- One strange thing was that if I emulated a mobile device in Firefox Developer Edition browser on Mac, the notifications permission was just denied without even getting a prompt, but that might just be a browser thing. 

- You can test this on https://gauntface.github.io/simple-push-demo/ by opening it in Firefox Developer and then goto developer tools and then click that phone icon on the top right (I guess you already know how to do this, but just in case 🤭)

- Also, I googled and in one of the posts they suggested to add gcm_id in manifest.json. I added a random gcm_id in the manifest but on further digging I realised this is not required anymore.

**Comment by marco-c** [comment]
I'm sorry, but this is not an issue due to this library, it's likely something wrong in your browsers or in the configuration of your browsers.

**Comment by khuezy** [comment]
@anamritraj Hi, this is likely due to your browser's _Privacy and security_ settings like marco-c said. If you go into Settings > Privacy/Security, there should be a Push Message option that you can enable if the browser supports Push Messages.
