### ISSUE TITLE
AWS Lambda setup

### ISSUE THREAD

**Issue by DSIdev** [web-push-libs/web-push#575]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: < Linux >
*Node Version*: <10.0>
*web-push Version*: <1.0.0>

> Please select any browsers that you are experiencing problems with:

- [x] Chrome
- [x] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem

> I am trying to send notification with my backed hosted on AWS lambda. The sendNotification call succeeds with 201 HTTP status but the notification doesn't get delivered. The same code works on local. Is there any additional step to get it working on AWS lambda?

# Expected

> Push notification should be delivered

# Features Used

- [x] VAPID Support
- [ ] GCM API Key
- [x] Sending with Payload

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

# Other

> Please put any remaining notes here.

**Comment by 4r7d3c0** [comment]
Did you see https://github.com/guerrerocarlos/serverless-web-push-notifications 
Seems to work there. I'm going to test today on lambda myself.

**Comment by marco-c** [comment]
It should just work the same way AFAIK. The Guardian is using this library in lambdas (see https://github.com/gdnmobilelab/pushkin).
