### ISSUE TITLE
Why convert app server key w/ urlBase64ToUint8Array

### ISSUE THREAD

**Issue by 4r7d3c0** [web-push-libs/web-push#577]
The spec states that the `applicationServerKey` can be passed as _DOMString_ in base64url which the lib generated already. why convert.
https://w3c.github.io/push-api/#pushsubscriptionoptions-interface

**Comment by 4r7d3c0** [comment]
ah i guess it was for the older chrome 
![Screenshot 2020-04-19 at 02 33 21](https://user-images.githubusercontent.com/60678477/79673861-41864080-81e6-11ea-9fbe-018f4eafead0.png)

**Comment by marco-c** [comment]
See also #558.
