### ISSUE TITLE
You must pass in a subscription with at least an endpoint.

### ISSUE THREAD

**Issue by EstopaceMA** [web-push-libs/web-push#584]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: <Linux | Windows | OS X>
*Node Version*: <4.2 | 6.0 | ...>
*web-push Version*: <1.0.0>

> Please select any browsers that you are experiencing problems with:

- [ /] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ /] Brave

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem

> I'm getting this error
![image](https://user-images.githubusercontent.com/37571727/82887353-78383f00-9f7a-11ea-8b9b-a0cfba45f38d.png)

# Expected

> I expect this to work flawlessly

# Features Used

- [ /] VAPID Support
- [ ] GCM API Key
- [ /] Sending with Payload

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

# Other

> Please put any remaining notes here.

**Comment by marco-c** [comment]
Please fill the issue template (especially the `Example / Reproduce Case` section), there is not enough information in this to be actionable.

**Comment by EstopaceMA** [comment]
Just a typo error on part of the body, just closing this issue, thank you for this @marco-c it really helps a lot 💯
