### ISSUE TITLE
Error in sending push notification to list of users

### ISSUE THREAD

**Issue by tycheexchange** [web-push-libs/web-push#600]
Hi guys,
I have followed all the relevant steps but when I send notification to our list of clients I receive following error.
the key in the authorization header does not correspond to the sender ID used to subscribe this user. Please ensure you are using the correct sender ID and server Key from the Firebase console.

```
"name": "WebPushError",
"message": "Received unexpected response code",
"statusCode": 403,
"body": "the key in the authorization header does not correspond to the sender ID used to subscribe this user. Please ensure you are using the correct sender ID and server Key from the Firebase console.\n",
```
my wpa is in app.example.com and my server is api.example.com

**Comment by marco-c** [comment]
It seems like you are using wrong sender ID and server Key, you'll need to carefully read the Firebase documentation, but this is not a problem with the library itself.

**Comment by JhonCordoba** [comment]
i have the same problem, i used the webpush.setGCMAPIKey(process.env.FCM_API_KEY as string) method to set the server key in the webpush library; but can you help me, saying me, where i have to set the sender ID?  i did not found any method like setSenderID() or something like this...
i have a web app that use firebase SDK, and a nodejs server where i am using this library (web-push)...

**Comment by alexonozor** [comment]
How do we set the sender Id and SERVER ID?
