### ISSUE TITLE
Suggestion: store VAPID details into WebPush instance

### ISSUE THREAD

**Issue by aletorrado** [web-push-libs/web-push#606]
Hi, I've noticed that VAPID details are being stored globally into the library scope. It seems that different VAPID details may be used anyways calling setVapidDetails every time before sending a notification, but that doesn't seem like a good practice.

It would be nicer to have those details embedded into the WebPush instance, while allowing multiple instances to be created more easily.

What do you think?

**Comment by marco-c** [comment]
Normally you'd use the same VAPID details for sending all notifications, that's why there is a setVapidDetails function.
You can still set them individually each time you send a notification by using the `vapidDetails` option.

So, you have both choices (set globally or set individually).
