### ISSUE TITLE
Service Worker registration failed:  TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vkings1** [web-push-libs/web-push#607]
![Screenshot from 2020-07-26 11-38-16 1](https://user-images.githubusercontent.com/22137536/88470909-eb3b4300-cf34-11ea-95d5-c578f4feb1c2.png)

**Comment by marco-c** [comment]
This is definitely not a problem with the library (it is server-side, so it can't in any way affect the service worker registration process).
