### ISSUE TITLE
In some area that FCM is block, If I want chrome receive the push message, how can I do?

### ISSUE THREAD

**Issue by Hotcapsicum** [web-push-libs/web-push#613]
I need push subscription in chrome, but my area can use FCM only by vpn.

At first, I used oneSignal, then I find that it need connection FCM.

Then I use web-push, and I use correct proxy, web-push(in node.js) can send message to FCM, but Chrome can't  receive this message. 

FCM and the browser will need to communicate with each other, then Chrome can get the message.

How can I do that chrome users can receive push messages without vpn?

**Comment by marco-c** [comment]
Unfortunately I don't think there is a way if connections to FCM are blocked in your area.
If the browser can't connect to FCM, then it can't receive notifications from FCM.

**Comment by Hotcapsicum** [comment]
so can I connections them by any proxy?
FCM must be directly connected to the browser,  proxy is no effet?

**Comment by marco-c** [comment]
The proxy is only useful for your server, as it sits between your server and FCM.
You can't force the browser to use a proxy.

**Comment by Hotcapsicum** [comment]
It seems that in China , Subscribe and push in Chrome is can't achieve.
But my boss said it's very important to our project. 
I'm going crazy
