### ISSUE TITLE
What exactly is the email used for in this example?

### ISSUE THREAD

**Issue by mayeaux** [web-push-libs/web-push#628]
```
webpush.setVapidDetails(
  'mailto:example@yourdomain.org',
  vapidKeys.publicKey,
  vapidKeys.privateKey
);
```

I see this example with `mailto:example@yourdomain.org` but I can't find anything in the docs about what that email is used for. Can that be explained somewhere? Thanks

**Comment by marco-c** [comment]
It could be used by the web push service provider to contact you in case there is a problem.

**Comment by mayeaux** [comment]
Thanks, is that part of the official spec? I'm trying to find info on that online but can't, thanks again!

**Comment by marco-c** [comment]
Yes! High-level description: https://blog.mozilla.org/services/2016/08/23/sending-vapid-identified-webpush-notifications-via-mozillas-push-service/. Spec: https://tools.ietf.org/html/rfc8292.
