### ISSUE TITLE
Can't catch error

### ISSUE THREAD

**Issue by mayeaux** [web-push-libs/web-push#629]
```
function sendPushNotification(subscription, urlEncodedData){
  try {
    webpush.sendNotification(subscription, urlEncodedData);
  } catch (err){
    console.log('err');
    console.log(err);
  }
}
```

This doesn't catch the error, it is still considered an 'unhandledRejection'. Why?

**Comment by marco-c** [comment]
`sendNotification` is asynchronous and returns a promise. If there is an error sendNotification doesn't throw an exception, but rejects the promise.
