### ISSUE TITLE
How to send push notifications to subscriptions gained without applicationServerKey

### ISSUE THREAD

**Issue by waleed-alsaady** [web-push-libs/web-push#644]
I have a lot of subscriptions from Firefox (endpoints, with the two keys). No vapid key was provided when calling pushManager.subscribe() method. When I try to call SendNotification with the subscription, payload but don't pass anything into options, I get 401 Unauthorized. Should I be passing any headers to replace the use of vapids?

**Comment by marco-c** [comment]
Do you know what version of Firefox they were using?

**Comment by waleed-alsaady** [comment]
> 
> 
> Do you know what version of Firefox they were using?

The subscriptions are all new from this year. I'm mostly testing on my own subscriptions ( I subscribe through OS then export the subscriptions details). The closest I've come is seeing how it's done here:
https://mozilla-services.github.io/WebPushDataTestPage/
The problem seems to be that the payload should Not be encrypted otherwise it excepts vapid keys, so I guess I need to write my own thing. Btw I'm using the C# library version. Anyway, I've decided this isn't so important as we have very little firefox subscriptions (more than 95% is chrome), owing to firefox auto hiding permission popup most of the time. So i'm just gonna concentrate on importing the chrome subscriptions and implementing double opt in for my own script to capture more firefox users.
