### ISSUE TITLE
Is it possible to use web push for on-premise deployment

### ISSUE THREAD

**Issue by yehia67** [web-push-libs/web-push#645]
Hey,
I need to use a built-in notification system for a private server.  Do you offer that?

**Comment by marco-c** [comment]
@yehia67 it is possible to use a custom web push service, at least in Firefox, but the browser itself needs to be configured to use it.

**Comment by yehia67** [comment]
Which customization do I need to do? if we are using chrome for example, What configurations we should implements? Could you please share any resources? Thanks.

**Comment by marco-c** [comment]
I'm not sure about Chrome. With Firefox, you'd need to change the `dom.push.serverURL` option from about:config to point to your web push service.

You can read https://medium.com/@jconlin_89117/roll-your-own-push-server-kind-of-7d36c997a768.

I'm closing the issue as it isn't really related to this library.
