### ISSUE TITLE
Remove all dependences and reduce code size to less than 300 lines of code

### ISSUE THREAD

**Issue by codermapuche** [web-push-libs/web-push#672]
Hello, i start a project at: https://github.com/codermapuche/webpush based on your code but removing all dependencies and reducing code size to less than 250 lines of code.

For my propuses it work, but maybe it be usefull to yours for use as base for a new version

If your like keep all dependences and the redudant code in your project, feel free to close this issue.

Have a nice day.

**Comment by marco-c** [comment]
Thanks @codermapuche.

Regarding dependencies, we have very few, and duplicating their code in the project doesn't seem a great idea from a maintenance perspective.

Regarding redundant code, I don't know what code you're referring to, but I'm happy to accept a PR to remove it.
