### ISSUE TITLE
Getting 401 Error for Microsoft Edge Browser for some of requests

### ISSUE THREAD

**Issue by pvagare** [web-push-libs/web-push#691]
# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: Windows
*Node Version*:  12/14
*web-push Version*: 3.4.5

> Please select any browsers that you are experiencing problems with:

- [x] Microsoft Edge

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem
I am getting following error for Microsft Edge browser while sending notification in Production. It is suddenly started coming from yesterday (31 Match 2022). Previsoly It was working properly. 
Do you think window service for notification got updated ?

If I subscribe today using Microsoft edge and sending notiication. It is going properly. Do you think old subscribers got expired ? 

Here is some  Subscriber subscription dates:
2021-09-26 11:41:22.895085
2021-06-11 08:41:21.57916
2021-04-21 18:56:24.705157
2021-09-23 03:26:21.735069
2021-07-22 17:26:20.000669
2022-01-03 13:58:03.211451

  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 401,
  headers: 
   { 'content-length': '0',
     'x-wns-msg-id': '2D3CCACF3E2F45C0',
     'x-wns-debug-trace': 'DB5PEPF0000A9B6',
     'ms-cv': 'SJnuur1cvE21MhLn56+qyA.0',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     'www-authenticate': 'bearer error="invalid_request",error_description="Invalid token"',
     date: 'Fri, 01 Apr 2022 06:57:42 GMT',
     connection: 'close' },

var subscription = 
{
    "endpoint": "https://wns2-db5p.notify.windows.com/w/?token=BQYAAABIwwWngWrUItaxn6WVXPp0rHkgK08E98839E69vJm%2buyzGoIocrJlCKdNqvxLVCkxcqWj%2fl5%2b8ocv4%2fFmXeqlCNLCsIPg8wvT9j5%2fn%2bvs83qAEjtJvTH2N8hAQ%2bwfi3%2bpNKvO68HfbaZPkRVSXPhBswS0L%2bNyfUu607EPY91X%2fToMU0xCP4IyckhqpJNBO%2brtbykzdFUT%2b%2bKaV4irinB0fKQwOmKWw47TotHpvepqe1dtXYf7YLwrkHUjrUi0ldM%2bsbOq6u9jUph%2baoA4AjFhMiuUNTWZnX0HnaQYu%2flpcUzwrFulaW3o1XfMceU%2bWM1uhbuGUDzKdzJvDQpDrH4vK",
    "expirationTime": null,
    "keys": {
        "p256dh": "BJValcswp5LNWomEleOMvj_s5Sl3X5SWCcYuu93bxcHMbmQ9vdcVbFUBVk6EnchLFKrKGzsR5mrJ-Ttmmq-YTnw",
        "auth": "xr0fHeA3-TiEyuA8J_isgQ"
    }
};

Please refer the token

# Expected

# Features Used

- [x] VAPID Support
# Other

> Please put any remaining notes here.

This is not coming for other browser.
Please can you help to sort the issue.

**Comment by pvagare** [comment]
Any updates ?

**Comment by AndyLi-Asana** [comment]
I'm seeing similar issues on my end, but I'm using `webpush-java`. Also, started around 3/31 for me, but I'm not sure if mine are specific to Edge.
 
```
HTTP/1.1 401 Unauthorized [Content-Length: 0, X-WNS-MSG-ID: 7E7A375C69F9B1B1, X-WNS-DEBUG-TRACE: BY3PEPF0000E99C, MS-CV: x1vk+4bZnECPw/9tajAnYA.0, Strict-Transport-Security: max-age=31536000; includeSubDomains, WWW-Authenticate: bearer error="invalid_request",error_description="Invalid token", Date: Fri, 01 Apr 2022 19:34:46 GMT] [Content-Length: 0,Chunked: false]
```

**Comment by marco-c** [comment]
This is unlikely to be related to the web-push library and more likely a problem with the Microsoft services.
