### ISSUE TITLE
Test with different versions of Firefox and Chromium

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#72]
We're currently testing with the Nightly versions. We should test at least with the release versions as well.

**Comment by marco-c** [comment]
WIP in #77.

**Comment by marco-c** [comment]
I'm testing on Firefox release and Chromium nightly for now. Adding Chromium release should be just a matter of implementing the code to download it, adding Firefox nightly now requires #21 (because the plain Selenium WebDriver doesn't work anymore with Firefox nightly).

**Comment by marco-c** [comment]
Note: we should remove the matrix on Travis and run multiple tests on a single Travis run, this way the tests should be faster (instead of spinning N builds, we would spin only 1 and so avoid N setups on Travis).

**Comment by marco-c** [comment]
#126 is going to make tests run both for Firefox release and Firefox beta.
Still missing:
- Chrome release;
- Firefox Dev Edition;
- Firefox Nightly.

Firefox Dev Edition and Firefox Nightly will require #21.

**Comment by gauntface** [comment]
If it would be helpful I can come up with a PR to use a similar approach as web-push-encryption.

I've also added some end-to-end tests (similar to what you currently have) on simple-push-demo that might be helpful here.

**Comment by marco-c** [comment]
> If it would be helpful I can come up with a PR to use a similar approach as web-push-encryption.

It would be great!

**Comment by marco-c** [comment]
@gauntface is taking care of this in #178.
