### ISSUE TITLE
[Question] Push Notifications on mobile

### ISSUE THREAD

**Issue by x9nico** [web-push-libs/web-push#725]
Hey!

I just have a question about Push notifications.
I would like to receive it on mobile to when I'm on a website with my phone. Someone have an idea ? :)

Thanks :)

**Comment by marco-c** [comment]
You can use the web-push API, there are many tutorials online.

**Comment by x9nico** [comment]
> You can use the web-push API, there are many tutorials online.

Can you send me one of them please ? I'm not finding any tutorials for mobile side.
