### ISSUE TITLE
postMessage is not defined

### ISSUE THREAD

**Issue by j2l** [web-push-libs/web-push#749]
# Setup
happens with simple callback code (see below) and also with the (old) web-push/test/demo

*Operating System*: Ubuntu 22.04
*Node Version*: 16.16.0
*web-push Version*: 3.5.0

- [x] Chrome http://locahost
- [x] Chromium http://locahost
- [ ] Firefox, unfortunately I can't get localhost 443 to work with it

# Problem
`postMessage` is not know in latest Chrome and Chromium versions.

# Expected
service-worker to send data to client page

# Features Used
- [x] VAPID Support

# Example / Reproduce Case
sw.js
```
self.addEventListener('push', function (event) {
   postMessage('test')
})
```

**Comment by marco-c** [comment]
The code you mention is not in this repo. Could you clarify what you mean?

**Comment by j2l** [comment]
It was 2022 man, I don't remember

**Comment by marco-c** [comment]
I guess this means you have been a satisfied user since then ;)

**Comment by j2l** [comment]
Haha, well, seeing that my ticket reaches someone after a solid YEAR is not really satisfying :smile:

**Comment by marco-c** [comment]
@j2l I'm contributing my time here, and I have very little of that ;)

**Comment by j2l** [comment]
@marco-c you're right. Thank you for your time.
