### ISSUE TITLE
Add support for WebPush notification in safari on MacOs and IOs using standard WebPush method.

### ISSUE THREAD

**Issue by sagardevadakar** [web-push-libs/web-push#754]
Apple announced that web push notifications are supporting in Safari 16 in macOS 13 with standard WebPush method as in other browsers. Also they will add support for iOS 16 next year (Early 2023). 

Currently I am using https://github.com/web-push-libs/web-push (node js) library for my application. but I could not found any changes for safari 16 in this library. So I am looking at the how to add supports for WebPush notification in safari 16 on MacOs and IOs.

**Comment by cedric-marcone** [comment]
Hello @sagardevadakar,

**Comment by sagardevadakar** [comment]
> Hello @sagardevadakar, Safari added support for standard web push as implemented by this lib. The work has been done on Apple side, nothing is to be done in this library. That's the beauty of the standards grinning

@cedric-marcone Thank You!
