### ISSUE TITLE
3.6.1 is not published on npm

### ISSUE THREAD

**Issue by dhardtke** [web-push-libs/web-push#796]
Similar to https://github.com/web-push-libs/web-push/issues/676 the last version (3.6.1) is not published on npm.

The last version is 3.5.0 (see https://www.npmjs.com/package/web-push?activeTab=dependencies).

Can you please publish the latest version?

Thanks.

**Comment by marco-c** [comment]
v3.6.1 published!
https://www.npmjs.com/package/web-push/v/3.6.1
