### ISSUE TITLE
Fix failure in encrypting/decrypting empty message on Node.js v0.12

### ISSUE THREAD

**Issue by marco-c** [web-push-libs/web-push#81]
I've disabled the test on 0.12 for now.

Here's an example failure:
[log.txt](https://github.com/marco-c/web-push/files/146542/log.txt)

**Comment by marco-c** [comment]
@martinthomson I guess this comes from http_ece, the error is `Error: Unsupported state or unable to authenticate data`.

I'm not sure how important supporting Node.js v0.12 is, but I'll keep this open.

**Comment by martinthomson** [comment]
Given the age of node 0.12 and that I'm unable to test it, maybe it's time to bump the minimum version.

**Comment by gauntface** [comment]
+1 for dropping 0.12 support.

**Comment by marco-c** [comment]
I would like to drop support for 0.12, but @eoger needed support for 0.10 (#150). As long as it doesn't cause too many problems for us, I'd like to keep supporting it.

@eoger are you still using 0.10?

**Comment by eoger** [comment]
Yes we're still using Node 0.10 on [fxa](https://github.com/mozilla/fxa-auth-server)

**Comment by marco-c** [comment]
Closing this as we don't really care if you can't encrypt/decrypt an empty message on Node.js 0.12.
