### ISSUE TITLE
Body not showing in push notification

### ISSUE THREAD

**Issue by TamarTal23** [web-push-libs/web-push#822]
*Operating System*: Windows 10
*Node Version*: 16.16
*web-push Version*: 3.5.0

Tried in Chrome and Edge

I'm getting push notifications with only the title and without the body from the payload.

This is my payload:

await webpush.sendNotification(subscription, JSON.stringify({ title: 'title', body: 'short text' }
));

![image](https://github.com/web-push-libs/web-push/assets/133848221/e7078a31-ab73-4485-a575-04f2211f2c9f)

**Comment by marco-c** [comment]
I think what you are showing in the popup depends on your code on the client side.

**Comment by TamarTal23** [comment]
it was a stupid typo in the client, thank you!!!
