### ISSUE TITLE
package.json: change of node >= 6 to node >= 16 should be a minor version upgrade?

### ISSUE THREAD

**Issue by DonHason** [web-push-libs/web-push#824]
**Just an idea, not a bug issue.**

The change from 

```
  "engines": {
    "node": ">= 6"
  }
```

to

```
  "engines": {
    "node": ">= 16"
  }
```

,in the patch version [3.3.6](https://github.com/web-push-libs/web-push/blob/v3.6.3/package.json), should be minor version upgrade to 3.7.0? 

For me it feels kinda harsh to dismiss 10 node versions in a patch version upgrade.

Feel free to close this issue, if you have a different opinion.

**Comment by marco-c** [comment]
It was a mistake to have `>= 6`, those Node versions were already not supported for a while.
