### ISSUE TITLE
Is there a changelog somewhere?

### ISSUE THREAD

**Issue by MumiaIrrequieta** [web-push-libs/web-push#842]
Hi, is there a changelog somewhere around here that I'm not seeing?
Also, is v3.2.2 really the latest release? I see a v3.6.5 tag, should everyone be using that?

Thank you,
João

**Comment by marco-c** [comment]
The latest version is 3.6.5. I forgot to generate releases on GitHub for a while, but they were all published on NPM and as tags.

The changelog is not available, but you can check out the list of commits between one version and another to figure out what changed. E.g. https://github.com/web-push-libs/web-push/compare/v3.6.4...v3.6.5.

**Comment by rynop** [comment]
@marco-c are breaking changes documented someplace, or are all features from 3.3.x -> 3.6.6 non-breaking?

It is very difficult for someone note intimately familiar with the codebase to do a diff between 2 versions and determine if all changes within are non-breaking...

**Comment by marco-c** [comment]
@rynop unfortunately it isn't documented anywhere. I don't think there were any breaking changes, but I'm not 100% sure. I'll try to mention it in the release notes from now on.
