### ISSUE TITLE
Dependency urlsafe-base64 uses Buffer unsafely (via http-ece)

### ISSUE THREAD

**Issue by wmaltmann** [web-push-libs/web-push#848]
**NOTE**: Please test in a least two browsers (i.e. Chrome and Firefox). This
helps with diagnosing problems quicker.

# Setup

> Please provide the following details, the more info you can provide the
> better.

*Operating System*: AWS Lambda | Windows
*Node Version*: 18.10.0
*web-push Version*: 3.6.2

> Please select any browsers that you are experiencing problems with:

- [x] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [x] Other - Edge

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

# Problem

> When calling sendNotification in Node18 I see the following console error:

```
ERROR	(node:14) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:195:11)
    at new Buffer (node:buffer:279:3)
    at Object.decode (/var/task/index.js:490:68353)
    at Object.validatePublicKey (/var/task/index.js:493:8952)
    at sendNotification (/var/task/index.js:497:4174)
    ...
```

There is a similar, fixed issue, (https://github.com/web-push-libs/web-push/issues/785) that handled removing direct calls to urlSafe-base64. There is also a child dependency on urlSafe-base64 in http-ece that causes the same issue. Workaround was to pull dependency code into my project and fix the call in http-ece.

# Expected

No console errors

# Features Used

- [ ] VAPID Support
- [ ] GCM API Key
- [x] Sending with Payload

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

```
import webpush from "web-push";

webpush.sendNotification(subscription, payload);
```

**Comment by wmaltmann** [comment]
Both are part of this same group, is this issue sufficient or should I duplicate it on the other repo?

**Comment by rpostulart** [comment]
Just upgrading to the latest nodejs  (18) runtime in AWS lamda solved the issue for me. I was on nodejs 16

**Comment by jondashkyle** [comment]
Also running into this, although strangely a few notifications will make it through, and then the error surfaces after some amount of time has passed.

```
(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Worth noting this is running Node 18—in response to the note above.

Happy to look into this further but figured I’d check in @wmaltmann.

**Comment by marco-c** [comment]
@jondashkyle if you want to help, you'd need to fix https://github.com/web-push-libs/encrypted-content-encoding/issues/68 in a similar fashion to https://github.com/web-push-libs/web-push/pull/813.

**Comment by wmaltmann** [comment]
I worked around it by making the change locally and pointing to my local version.

**Comment by marco-c** [comment]
@wmaltmann could you submit a PR? That would benefit everyone!
