### ISSUE TITLE
Notifications not always shown in MacOS Chrome

### ISSUE THREAD

**Issue by c4b4d4** [web-push-libs/web-push#855]
# Problem

Web push notifications are delivered but they are not _always_ being displayed, they mostly land 99% of the time into the hidden side-panel Notifications. So users never know when they get notification.

I've checked my MacOS notifications settings, and they are turned on

![Screenshot 2023-09-25 at 17 36 27](https://github.com/web-push-libs/web-push/assets/375183/5bf46fd2-1750-4c37-bc00-dae6f5b373d6)

![Screenshot 2023-09-25 at 17 36 41](https://github.com/web-push-libs/web-push/assets/375183/50b83138-c820-40cd-8e53-3125bbbcd8bf)

Is there a configuration to force the notifications to be shown? I've tried adding `{ urgency: "high" }` with no luck. Is this a known issue in MacOS + Chrome browsers?

Is weird, because I've seen notifications from other websites and even from my own service, but they are random. I don't know what makes them show on screen and what makes them be sent to the hidden notification center.

# Specs

*Operating System*: MacOS
*Node Version*: 16.15
*web-push Version*: 3.6.6

- [X] Chrome

# Features Used

- [X] VAPID Support
- [X] Sending with Payload

**Comment by marco-c** [comment]
Yes, unfortunately there's nothing we can do in this lib to help with this.
