### ISSUE TITLE
How to define target endpoint for notification

### ISSUE THREAD

**Issue by MarcusHSmith** [web-push-libs/web-push#860]
# Problem

> Please explain what behaviour you are seeing.

How do I define the endpoint when a user clicks the notification? I'm struggling to find documentation about how the payload or options should be structured in `webpush.sendNotification`

Thanks

**Comment by marco-c** [comment]
I suggest looking at the example on MDN or the Service Worker Cookbook: https://github.com/web-push-libs/web-push#help.
