### ISSUE TITLE
FCM legacy api shutdown

### ISSUE THREAD

**Issue by ok-sm** [web-push-libs/web-push#893]
# Setup

> Please provide the following details, the more info you can provide the
> better.

Not applicable.

*Operating System*: Not applicable.
*Node Version*: Not applicable.
*web-push Version*: Not applicable.

> Please select any browsers that you are experiencing problems with:

- [X] Chrome
- [ ] Firefox
- [ ] Opera for Android
- [ ] Samsung Internet Browser
- [ ] Other

> Please list the browsers you are have tested this, including the version
> of the browser (i.e. Chrome Beta, Firefox Beta etc).

All chrome versions.

# Problem

FCM legacy api shutdown.

# Expected

I would like to know how will your API work when Google shuts down their's legacy API on June 20, 2024. 
We have a lot of tokens generated by this API and after trying to migrate to FCM v1 API they doesn't seem to work.
FCM v1 API returns UNREGISTERED when sending requests. We imported VAPID key pair used to generate those tokens.

# Features Used

- [X] VAPID Support
- [ ] GCM API Key
- [X] Sending with Payload

# Example / Reproduce Case

> Please provide a code sample that reproduces the issue. If there is a
> repository that reproduces the issue please put the link here.

# Other

**Comment by marco-c** [comment]
The library is only implementing the web-push standard, there's nothing we can do on our end.
Google might come up with a way to keep the old subscriptions working, but this is a question for them. You could ask their support.
