### ISSUE TITLE
Will the code still work when FCM API is removed in Jun-2024?

### ISSUE THREAD

**Issue by goldentom66** [web-push-libs/web-push#901]
In https://firebase.google.com/docs/cloud-messaging/migrate-v1

It mentioned that FCM API "https://fcm.googleapis.com/fcm/send" will be removed.
Will this impact this project?

**Comment by yoruponder** [comment]
+1 also want to know

**Comment by marco-c** [comment]
This projects implements the web-push standard, so it is not affected by changes in third-party services (unless the third-party services decide to start implementing a protocol that is not standard).
